export const phrases_ES = [
  "Un café con leche, por favor",
  "Un té sin azúcar, por favor",
  "Un vaso de agua, por favor",
  "Quiero un café pequeño",
  "Quiero un café grande",
  "Quiero un café con azúcar",
  "Quiero un café sin leche",
  "Quiero un café con leche y azúcar",
  "Quiero un té con limón",
  "Quiero un té sin leche",
  "Quiero un chocolate caliente",
  "Quiero un jugo de naranja",
  "Quiero un sándwich de queso",
  "Quiero un sándwich de jamón",
  "Quiero un pastel de manzana",
  "Quiero una galleta",
  "Quiero una tostada con mantequilla",
  "Quiero una tostada con mermelada",
  "Quiero un croissant",
  "Quiero un café descafeinado",
  "No quiero azúcar",
  "No quiero leche",
  "No quiero café",
  "No quiero té",
  "No quiero nada",
  "No quiero un sándwich",
  "No quiero un pastel",
  "No quiero un jugo",
  "No quiero un chocolate",
  "No quiero una galleta",
  "¿Dónde está el baño?",
  "¿Cuánto cuesta?",
  "¿Cuánto cuesta el café?",
  "¿Cuánto cuesta el té?",
  "¿Cuánto cuesta el pastel?",
  "¿Cuánto cuesta el jugo?",
  "¿Cuánto cuesta el sándwich?",
  "¿Cuánto cuesta la galleta?",
  "¿Cuánto cuesta el chocolate?",
  "¿Cuánto cuesta el agua?",
  "¿Tienen café descafeinado?",
  "¿Tienen té verde?",
  "¿Tienen jugo de manzana?",
  "¿Tienen pastel de chocolate?",
  "¿Tienen croissants?",
  "¿Tienen leche de soja?",
  "¿Tienen azúcar moreno?",
  "¿Tienen miel?",
  "¿Tienen pan integral?",
  "¿Puedo pagar con tarjeta?",
  "¿Puedo pagar en efectivo?",
  "¿Puedo sentarme aquí?",
  "¿Puedo tener una servilleta?",
  "¿Puedo tener una cuchara?",
  "¿Puedo tener un tenedor?",
  "¿Puedo tener un cuchillo?",
  "¿Puedo tener un vaso?",
  "¿Puedo tener una taza?",
  "¿Puedo tener una silla?",
  "Una mesa para dos, por favor",
  "Una mesa para uno, por favor",
  "Una mesa junto a la ventana",
  "Una mesa afuera, por favor",
  "Quiero reservar una mesa",
  "Quiero pagar ahora",
  "Quiero pagar después",
  "La cuenta, por favor",
  "El menú, por favor",
  "¿Tienen menú en inglés?",
  "¿Tienen menú en alemán?",
  "¿Tienen menú vegetariano?",
  "¿Tienen menú vegano?",
  "¿Tienen leche sin lactosa?",
  "¿Tienen leche de almendra?",
  "¿Tienen leche de avena?",
  "¿Tienen leche de coco?",
  "¿Está abierto?",
  "¿Está cerrado?",
  "¿Abren mañana?",
  "¿Cierran hoy?",
  "¿Hay wifi aquí?",
  "¿Hay enchufe aquí?",
  "¿Hay espacio afuera?",
  "¿Hay espacio adentro?",
  "¿Está ocupado?",
  "¿Está libre?",
  "¿Está limpio?",
  "¿Está sucio?",
  "¿Está caliente?",
  "¿Está frío?",
  "¿Está dulce?",
  "¿Está amargo?",
  "¿Está salado?",
  "¿Está listo?",
  "¿Está fresco?",
  "¿Está seco?",
  "¿Está mojado?",
  "¿Está rico?",
  "¿Está malo?",
  "¿Está bien?",
  "¿Está mal?"
];

export const phrases_EN = [
  "A coffee with milk, please",
  "A tea without sugar, please",
  "A glass of water, please",
  "I want a small coffee",
  "I want a large coffee",
  "I want a coffee with sugar",
  "I want a coffee without milk",
  "I want a coffee with milk and sugar",
  "I want a tea with lemon",
  "I want a tea without milk",
  "I want a hot chocolate",
  "I want an orange juice",
  "I want a cheese sandwich",
  "I want a ham sandwich",
  "I want an apple pie",
  "I want a cookie",
  "I want toast with butter",
  "I want toast with jam",
  "I want a croissant",
  "I want a decaf coffee",
  "I don’t want sugar",
  "I don’t want milk",
  "I don’t want coffee",
  "I don’t want tea",
  "I don’t want anything",
  "I don’t want a sandwich",
  "I don’t want a cake",
  "I don’t want juice",
  "I don’t want chocolate",
  "I don’t want a cookie",
  "Where is the bathroom?",
  "How much is it?",
  "How much is the coffee?",
  "How much is the tea?",
  "How much is the cake?",
  "How much is the juice?",
  "How much is the sandwich?",
  "How much is the cookie?",
  "How much is the chocolate?",
  "How much is the water?",
  "Do you have decaf coffee?",
  "Do you have green tea?",
  "Do you have apple juice?",
  "Do you have chocolate cake?",
  "Do you have croissants?",
  "Do you have soy milk?",
  "Do you have brown sugar?",
  "Do you have honey?",
  "Do you have whole wheat bread?",
  "Can I pay with card?",
  "Can I pay in cash?",
  "Can I sit here?",
  "Can I have a napkin?",
  "Can I have a spoon?",
  "Can I have a fork?",
  "Can I have a knife?",
  "Can I have a glass?",
  "Can I have a cup?",
  "Can I have a chair?",
  "A table for two, please",
  "A table for one, please",
  "A table by the window",
  "A table outside, please",
  "I want to reserve a table",
  "I want to pay now",
  "I want to pay later",
  "The bill, please",
  "The menu, please",
  "Do you have a menu in English?",
  "Do you have a menu in German?",
  "Do you have a vegetarian menu?",
  "Do you have a vegan menu?",
  "Do you have lactose-free milk?",
  "Do you have almond milk?",
  "Do you have oat milk?",
  "Do you have coconut milk?",
  "Is it open?",
  "Is it closed?",
  "Are you open tomorrow?",
  "Are you closing today?",
  "Is there wifi here?",
  "Is there a power outlet here?",
  "Is there space outside?",
  "Is there space inside?",
  "Is it occupied?",
  "Is it free?",
  "Is it clean?",
  "Is it dirty?",
  "Is it hot?",
  "Is it cold?",
  "Is it sweet?",
  "Is it bitter?",
  "Is it salty?",
  "Is it ready?",
  "Is it fresh?",
  "Is it dry?",
  "Is it wet?",
  "Is it tasty?",
  "Is it bad?",
  "Is it good?",
  "Is it wrong?"
];

export const phrases_DE = [
  "Einen Kaffee mit Milch, bitte",
  "Einen Tee ohne Zucker, bitte",
  "Ein Glas Wasser, bitte",
  "Ich möchte einen kleinen Kaffee",
  "Ich möchte einen großen Kaffee",
  "Ich möchte einen Kaffee mit Zucker",
  "Ich möchte einen Kaffee ohne Milch",
  "Ich möchte einen Kaffee mit Milch und Zucker",
  "Ich möchte einen Tee mit Zitrone",
  "Ich möchte einen Tee ohne Milch",
  "Ich möchte eine heiße Schokolade",
  "Ich möchte einen Orangensaft",
  "Ich möchte ein Käse-Sandwich",
  "Ich möchte ein Schinken-Sandwich",
  "Ich möchte einen Apfelkuchen",
  "Ich möchte einen Keks",
  "Ich möchte einen Toast mit Butter",
  "Ich möchte einen Toast mit Marmelade",
  "Ich möchte ein Croissant",
  "Ich möchte einen entkoffeinierten Kaffee",
  "Ich möchte keinen Zucker",
  "Ich möchte keine Milch",
  "Ich möchte keinen Kaffee",
  "Ich möchte keinen Tee",
  "Ich möchte nichts",
  "Ich möchte kein Sandwich",
  "Ich möchte keinen Kuchen",
  "Ich möchte keinen Saft",
  "Ich möchte keine Schokolade",
  "Ich möchte keinen Keks",
  "Wo ist die Toilette?",
  "Wie viel kostet es?",
  "Wie viel kostet der Kaffee?",
  "Wie viel kostet der Tee?",
  "Wie viel kostet der Kuchen?",
  "Wie viel kostet der Saft?",
  "Wie viel kostet das Sandwich?",
  "Wie viel kostet der Keks?",
  "Wie viel kostet die Schokolade?",
  "Wie viel kostet das Wasser?",
  "Haben Sie entkoffeinierten Kaffee?",
  "Haben Sie grünen Tee?",
  "Haben Sie Apfelsaft?",
  "Haben Sie Schokoladenkuchen?",
  "Haben Sie Croissants?",
  "Haben Sie Sojamilch?",
  "Haben Sie braunen Zucker?",
  "Haben Sie Honig?",
  "Haben Sie Vollkornbrot?",
  "Kann ich mit Karte bezahlen?",
  "Kann ich bar bezahlen?",
  "Kann ich hier sitzen?",
  "Kann ich eine Serviette haben?",
  "Kann ich einen Löffel haben?",
  "Kann ich eine Gabel haben?",
  "Kann ich ein Messer haben?",
  "Kann ich ein Glas haben?",
  "Kann ich eine Tasse haben?",
  "Kann ich einen Stuhl haben?",
  "Ein Tisch für zwei, bitte",
  "Ein Tisch für eine Person, bitte",
  "Ein Tisch am Fenster",
  "Ein Tisch draußen, bitte",
  "Ich möchte einen Tisch reservieren",
  "Ich möchte jetzt bezahlen",
  "Ich möchte später bezahlen",
  "Die Rechnung, bitte",
  "Die Speisekarte, bitte",
  "Haben Sie eine Speisekarte auf Englisch?",
  "Haben Sie eine Speisekarte auf Deutsch?",
  "Haben Sie eine vegetarische Speisekarte?",
  "Haben Sie eine vegane Speisekarte?",
  "Haben Sie laktosefreie Milch?",
  "Haben Sie Mandelmilch?",
  "Haben Sie Hafermilch?",
  "Haben Sie Kokosmilch?",
  "Ist es geöffnet?",
  "Ist es geschlossen?",
  "Öffnen Sie morgen?",
  "Schließen Sie heute?",
  "Gibt es hier WLAN?",
  "Gibt es hier eine Steckdose?",
  "Gibt es draußen Platz?",
  "Gibt es drinnen Platz?",
  "Ist es besetzt?",
  "Ist es frei?",
  "Ist es sauber?",
  "Ist es schmutzig?",
  "Ist es heiß?",
  "Ist es kalt?",
  "Ist es süß?",
  "Ist es bitter?",
  "Ist es salzig?",
  "Ist es fertig?",
  "Ist es frisch?",
  "Ist es trocken?",
  "Ist es nass?",
  "Ist es lecker?",
  "Ist es schlecht?",
  "Ist es gut?",
  "Ist es schlecht?"
];

export const phrases_IT = [
  "Un caffè con latte, per favore",
  "Un tè senza zucchero, per favore",
  "Un bicchiere d'acqua, per favore",
  "Voglio un caffè piccolo",
  "Voglio un caffè grande",
  "Voglio un caffè con zucchero",
  "Voglio un caffè senza latte",
  "Voglio un caffè con latte e zucchero",
  "Voglio un tè con limone",
  "Voglio un tè senza latte",
  "Voglio una cioccolata calda",
  "Voglio un succo d'arancia",
  "Voglio un panino al formaggio",
  "Voglio un panino al prosciutto",
  "Voglio una torta di mele",
  "Voglio un biscotto",
  "Voglio una fetta di pane tostato con burro",
  "Voglio una fetta di pane tostato con marmellata",
  "Voglio un cornetto",
  "Voglio un caffè decaffeinato",
  "Non voglio zucchero",
  "Non voglio latte",
  "Non voglio caffè",
  "Non voglio tè",
  "Non voglio niente",
  "Non voglio un panino",
  "Non voglio una torta",
  "Non voglio un succo",
  "Non voglio una cioccolata",
  "Non voglio un biscotto",
  "Dove si trova il bagno?",
  "Quanto costa?",
  "Quanto costa il caffè?",
  "Quanto costa il tè?",
  "Quanto costa la torta?",
  "Quanto costa il succo?",
  "Quanto costa il panino?",
  "Quanto costa il biscotto?",
  "Quanto costa la cioccolata?",
  "Quanto costa l'acqua?",
  "Avete caffè decaffeinato?",
  "Avete tè verde?",
  "Avete succo di mela?",
  "Avete torta al cioccolato?",
  "Avete cornetti?",
  "Avete latte di soia?",
  "Avete zucchero di canna?",
  "Avete miele?",
  "Avete pane integrale?",
  "Posso pagare con carta?",
  "Posso pagare in contanti?",
  "Posso sedermi qui?",
  "Posso avere un tovagliolo?",
  "Posso avere un cucchiaio?",
  "Posso avere una forchetta?",
  "Posso avere un coltello?",
  "Posso avere un bicchiere?",
  "Posso avere una tazza?",
  "Posso avere una sedia?",
  "Un tavolo per due, per favore",
  "Un tavolo per uno, per favore",
  "Un tavolo vicino alla finestra",
  "Un tavolo fuori, per favore",
  "Voglio prenotare un tavolo",
  "Voglio pagare adesso",
  "Voglio pagare dopo",
  "Il conto, per favore",
  "Il menù, per favore",
  "Avete il menù in inglese?",
  "Avete il menù in tedesco?",
  "Avete un menù vegetariano?",
  "Avete un menù vegano?",
  "Avete latte senza lattosio?",
  "Avete latte di mandorla?",
  "Avete latte d'avena?",
  "Avete latte di cocco?",
  "È aperto?",
  "È chiuso?",
  "Aprite domani?",
  "Chiudete oggi?",
  "C'è il wifi qui?",
  "C'è una presa qui?",
  "C'è spazio fuori?",
  "C'è spazio dentro?",
  "È occupato?",
  "È libero?",
  "È pulito?",
  "È sporco?",
  "È caldo?",
  "È freddo?",
  "È dolce?",
  "È amaro?",
  "È salato?",
  "È pronto?",
  "È fresco?",
  "È secco?",
  "È bagnato?",
  "È buono?",
  "È cattivo?",
  "Va bene?",
  "Va male?"
];
