export const phrases_ES = [
  "Él es mi papá, Max",
  "Ella es mi hermana",
  "Él no es mi esposo",
  "¿Esa es tu abuela?",
  "Mi hermano es panadero",
  "¿Es tu hermano panadero?",
  "Mi hermana es maestra",
  "No, mi hermano no es carpintero",
  "Él es mi tío",
  "Ella es mi tía",
  "¿Es tu primo músico?",
  "Mi primo es músico",
  "Mi madre es doctora",
  "¿Tu madre es doctora?",
  "Mi padre es maestro",
  "No, mi padre no es maestro",
  "Ella es mi amiga",
  "Él es mi amigo",
  "¿Es tu amigo vendedor?",
  "Mi amigo es vendedor",
  "Mi abuelo es carpintero",
  "¿Tu abuelo es carpintero?",
  "Mi abuela es cocinera",
  "Ella no es mi abuela",
  "Él es mi sobrino",
  "Ella es mi sobrina",
  "¿Es tu sobrina estudiante?",
  "Mi sobrina es estudiante",
  "Mi hermano es estudiante",
  "¿Tu hermano es estudiante?",
  "Mi hermana no es estudiante",
  "Él es mi primo",
  "Ella es mi prima",
  "¿Es tu prima doctora?",
  "Mi prima es doctora",
  "Mi tío es músico",
  "¿Tu tío es músico?",
  "Mi tía es enfermera",
  "Ella no es mi tía",
  "Él es mi cuñado",
  "Ella es mi cuñada",
  "¿Es tu cuñado maestro?",
  "Mi cuñado es maestro",
  "Mi cuñada es panadera",
  "¿Tu cuñada es panadera?",
  "Mi padre no es carpintero",
  "Mi madre no es cocinera",
  "¿Es tu padre doctor?",
  "¿Es tu madre enfermera?",
  "Mi amigo es estudiante",
  "Mi amiga es estudiante",
  "¿Tu amigo es músico?",
  "¿Tu amiga es doctora?",
  "Mi abuelo no es vendedor",
  "Mi abuela no es maestra",
  "Él es mi esposo",
  "Ella es mi esposa",
  "¿Es tu esposa doctora?",
  "¿Es tu esposo maestro?",
  "Mi esposo es carpintero",
  "Mi esposa es cocinera",
  "Mi hermano es doctor",
  "Mi hermana es enfermera",
  "¿Tu hermano es doctor?",
  "¿Tu hermana es enfermera?",
  "Mi primo no es músico",
  "Mi prima no es doctora",
  "Él es mi vecino",
  "Ella es mi vecina",
  "¿Es tu vecino panadero?",
  "¿Es tu vecina maestra?",
  "Mi vecino es panadero",
  "Mi vecina es maestra",
  "Mi sobrino es músico",
  "Mi sobrina es doctora",
  "¿Tu sobrino es músico?",
  "¿Tu sobrina es doctora?",
  "Mi tío no es carpintero",
  "Mi tía no es cocinera",
  "Él es mi profesor",
  "Ella es mi profesora",
  "¿Es tu profesor músico?",
  "¿Es tu profesora doctora?",
  "Mi profesor es músico",
  "Mi profesora es doctora",
  "Mi padre es músico",
  "Mi madre es maestra",
  "¿Tu padre es músico?",
  "¿Tu madre es maestra?",
  "Mi abuelo es doctor",
  "Mi abuela es enfermera",
  "¿Tu abuelo es doctor?",
  "¿Tu abuela es enfermera?",
  "Mi amigo no es carpintero",
  "Mi amiga no es cocinera",
  "Él es mi jefe",
  "Ella es mi jefa"
];

export const phrases_EN = [
  "He is my dad, Max",
  "She is my sister",
  "He is not my husband",
  "Is that your grandmother?",
  "My brother is a baker",
  "Is your brother a baker?",
  "My sister is a teacher",
  "No, my brother is not a carpenter",
  "He is my uncle",
  "She is my aunt",
  "Is your cousin a musician?",
  "My cousin is a musician",
  "My mother is a doctor",
  "Is your mother a doctor?",
  "My father is a teacher",
  "No, my father is not a teacher",
  "She is my friend",
  "He is my friend",
  "Is your friend a salesman?",
  "My friend is a salesman",
  "My grandfather is a carpenter",
  "Is your grandfather a carpenter?",
  "My grandmother is a cook",
  "She is not my grandmother",
  "He is my nephew",
  "She is my niece",
  "Is your niece a student?",
  "My niece is a student",
  "My brother is a student",
  "Is your brother a student?",
  "My sister is not a student",
  "He is my cousin",
  "She is my cousin",
  "Is your cousin a doctor?",
  "My cousin is a doctor",
  "My uncle is a musician",
  "Is your uncle a musician?",
  "My aunt is a nurse",
  "She is not my aunt",
  "He is my brother-in-law",
  "She is my sister-in-law",
  "Is your brother-in-law a teacher?",
  "My brother-in-law is a teacher",
  "My sister-in-law is a baker",
  "Is your sister-in-law a baker?",
  "My father is not a carpenter",
  "My mother is not a cook",
  "Is your father a doctor?",
  "Is your mother a nurse?",
  "My friend is a student",
  "My female friend is a student",
  "Is your friend a musician?",
  "Is your female friend a doctor?",
  "My grandfather is not a salesman",
  "My grandmother is not a teacher",
  "He is my husband",
  "She is my wife",
  "Is your wife a doctor?",
  "Is your husband a teacher?",
  "My husband is a carpenter",
  "My wife is a cook",
  "My brother is a doctor",
  "My sister is a nurse",
  "Is your brother a doctor?",
  "Is your sister a nurse?",
  "My cousin is not a musician",
  "My female cousin is not a doctor",
  "He is my neighbor",
  "She is my neighbor",
  "Is your neighbor a baker?",
  "Is your female neighbor a teacher?",
  "My neighbor is a baker",
  "My female neighbor is a teacher",
  "My nephew is a musician",
  "My niece is a doctor",
  "Is your nephew a musician?",
  "Is your niece a doctor?",
  "My uncle is not a carpenter",
  "My aunt is not a cook",
  "He is my teacher",
  "She is my teacher",
  "Is your teacher a musician?",
  "Is your female teacher a doctor?",
  "My teacher is a musician",
  "My female teacher is a doctor",
  "My father is a musician",
  "My mother is a teacher",
  "Is your father a musician?",
  "Is your mother a teacher?",
  "My grandfather is a doctor",
  "My grandmother is a nurse",
  "Is your grandfather a doctor?",
  "Is your grandmother a nurse?",
  "My friend is not a carpenter",
  "My female friend is not a cook",
  "He is my boss",
  "She is my boss"
];

export const phrases_DE = [
  "Er ist mein Vater, Max",
  "Sie ist meine Schwester",
  "Er ist nicht mein Ehemann",
  "Ist das deine Großmutter?",
  "Mein Bruder ist Bäcker",
  "Ist dein Bruder Bäcker?",
  "Meine Schwester ist Lehrerin",
  "Nein, mein Bruder ist kein Tischler",
  "Er ist mein Onkel",
  "Sie ist meine Tante",
  "Ist dein Cousin Musiker?",
  "Mein Cousin ist Musiker",
  "Meine Mutter ist Ärztin",
  "Ist deine Mutter Ärztin?",
  "Mein Vater ist Lehrer",
  "Nein, mein Vater ist kein Lehrer",
  "Sie ist meine Freundin",
  "Er ist mein Freund",
  "Ist dein Freund Verkäufer?",
  "Mein Freund ist Verkäufer",
  "Mein Großvater ist Tischler",
  "Ist dein Großvater Tischler?",
  "Meine Großmutter ist Köchin",
  "Sie ist nicht meine Großmutter",
  "Er ist mein Neffe",
  "Sie ist meine Nichte",
  "Ist deine Nichte Studentin?",
  "Meine Nichte ist Studentin",
  "Mein Bruder ist Student",
  "Ist dein Bruder Student?",
  "Meine Schwester ist keine Studentin",
  "Er ist mein Cousin",
  "Sie ist meine Cousine",
  "Ist deine Cousine Ärztin?",
  "Meine Cousine ist Ärztin",
  "Mein Onkel ist Musiker",
  "Ist dein Onkel Musiker?",
  "Meine Tante ist Krankenschwester",
  "Sie ist nicht meine Tante",
  "Er ist mein Schwager",
  "Sie ist meine Schwägerin",
  "Ist dein Schwager Lehrer?",
  "Mein Schwager ist Lehrer",
  "Meine Schwägerin ist Bäckerin",
  "Ist deine Schwägerin Bäckerin?",
  "Mein Vater ist kein Tischler",
  "Meine Mutter ist keine Köchin",
  "Ist dein Vater Arzt?",
  "Ist deine Mutter Krankenschwester?",
  "Mein Freund ist Student",
  "Meine Freundin ist Studentin",
  "Ist dein Freund Musiker?",
  "Ist deine Freundin Ärztin?",
  "Mein Großvater ist kein Verkäufer",
  "Meine Großmutter ist keine Lehrerin",
  "Er ist mein Ehemann",
  "Sie ist meine Ehefrau",
  "Ist deine Ehefrau Ärztin?",
  "Ist dein Ehemann Lehrer?",
  "Mein Ehemann ist Tischler",
  "Meine Ehefrau ist Köchin",
  "Mein Bruder ist Arzt",
  "Meine Schwester ist Krankenschwester",
  "Ist dein Bruder Arzt?",
  "Ist deine Schwester Krankenschwester?",
  "Mein Cousin ist kein Musiker",
  "Meine Cousine ist keine Ärztin",
  "Er ist mein Nachbar",
  "Sie ist meine Nachbarin",
  "Ist dein Nachbar Bäcker?",
  "Ist deine Nachbarin Lehrerin?",
  "Mein Nachbar ist Bäcker",
  "Meine Nachbarin ist Lehrerin",
  "Mein Neffe ist Musiker",
  "Meine Nichte ist Ärztin",
  "Ist dein Neffe Musiker?",
  "Ist deine Nichte Ärztin?",
  "Mein Onkel ist kein Tischler",
  "Meine Tante ist keine Köchin",
  "Er ist mein Lehrer",
  "Sie ist meine Lehrerin",
  "Ist dein Lehrer Musiker?",
  "Ist deine Lehrerin Ärztin?",
  "Mein Lehrer ist Musiker",
  "Meine Lehrerin ist Ärztin",
  "Mein Vater ist Musiker",
  "Meine Mutter ist Lehrerin",
  "Ist dein Vater Musiker?",
  "Ist deine Mutter Lehrerin?",
  "Mein Großvater ist Arzt",
  "Meine Großmutter ist Krankenschwester",
  "Ist dein Großvater Arzt?",
  "Ist deine Großmutter Krankenschwester?",
  "Mein Freund ist kein Tischler",
  "Meine Freundin ist keine Köchin",
  "Er ist mein Chef",
  "Sie ist meine Chefin"
];

export const phrases_IT = [
  "Lui è mio papà, Max",
  "Lei è mia sorella",
  "Lui non è mio marito",
  "Quella è tua nonna?",
  "Mio fratello è panettiere",
  "Tuo fratello è panettiere?",
  "Mia sorella è maestra",
  "No, mio fratello non è falegname",
  "Lui è mio zio",
  "Lei è mia zia",
  "Tuo cugino è musicista?",
  "Mio cugino è musicista",
  "Mia madre è dottoressa",
  "Tua madre è dottoressa?",
  "Mio padre è maestro",
  "No, mio padre non è maestro",
  "Lei è mia amica",
  "Lui è mio amico",
  "Il tuo amico è venditore?",
  "Il mio amico è venditore",
  "Mio nonno è falegname",
  "Tuo nonno è falegname?",
  "Mia nonna è cuoca",
  "Lei non è mia nonna",
  "Lui è mio nipote",
  "Lei è mia nipote",
  "Tua nipote è studentessa?",
  "Mia nipote è studentessa",
  "Mio fratello è studente",
  "Tuo fratello è studente?",
  "Mia sorella non è studentessa",
  "Lui è mio cugino",
  "Lei è mia cugina",
  "Tua cugina è dottoressa?",
  "Mia cugina è dottoressa",
  "Mio zio è musicista",
  "Tuo zio è musicista?",
  "Mia zia è infermiera",
  "Lei non è mia zia",
  "Lui è mio cognato",
  "Lei è mia cognata",
  "Tuo cognato è maestro?",
  "Mio cognato è maestro",
  "Mia cognata è panettiera",
  "Tua cognata è panettiera?",
  "Mio padre non è falegname",
  "Mia madre non è cuoca",
  "Tuo padre è dottore?",
  "Tua madre è infermiera?",
  "Il mio amico è studente",
  "La mia amica è studentessa",
  "Il tuo amico è musicista?",
  "La tua amica è dottoressa?",
  "Mio nonno non è venditore",
  "Mia nonna non è maestra",
  "Lui è mio marito",
  "Lei è mia moglie",
  "Tua moglie è dottoressa?",
  "Tuo marito è maestro?",
  "Mio marito è falegname",
  "Mia moglie è cuoca",
  "Mio fratello è dottore",
  "Mia sorella è infermiera",
  "Tuo fratello è dottore?",
  "Tua sorella è infermiera?",
  "Mio cugino non è musicista",
  "Mia cugina non è dottoressa",
  "Lui è mio vicino",
  "Lei è la mia vicina",
  "Il tuo vicino è panettiere?",
  "La tua vicina è maestra?",
  "Il mio vicino è panettiere",
  "La mia vicina è maestra",
  "Mio nipote è musicista",
  "Mia nipote è dottoressa",
  "Tuo nipote è musicista?",
  "Tua nipote è dottoressa?",
  "Mio zio non è falegname",
  "Mia zia non è cuoca",
  "Lui è il mio professore",
  "Lei è la mia professoressa",
  "Il tuo professore è musicista?",
  "La tua professoressa è dottoressa?",
  "Il mio professore è musicista",
  "La mia professoressa è dottoressa",
  "Mio padre è musicista",
  "Mia madre è maestra",
  "Tuo padre è musicista?",
  "Tua madre è maestra?",
  "Mio nonno è dottore",
  "Mia nonna è infermiera",
  "Tuo nonno è dottore?",
  "Tua nonna è infermiera?",
  "Il mio amico non è falegname",
  "La mia amica non è cuoca",
  "Lui è il mio capo",
  "Lei è la mia capa"
];

export const phrases_FR = [
  "Il est mon papa, Max",
  "Elle est ma sœur",
  "Il n'est pas mon mari",
  "Est-ce que c'est ta grand-mère?",
  "Mon frère est boulanger",
  "Est-ce que ton frère est boulanger?",
  "Ma sœur est maîtresse",
  "Non, mon frère n'est pas charpentier",
  "Il est mon oncle",
  "Elle est ma tante",
  "Est-ce que ton cousin est musicien?",
  "Mon cousin est musicien",
  "Ma mère est docteur",
  "Est-ce que ta mère est docteur?",
  "Mon père est maître",
  "Non, mon père n'est pas maître",
  "Elle est mon amie",
  "Il est mon ami",
  "Est-ce que ton ami est vendeur?",
  "Mon ami est vendeur",
  "Mon grand-père est charpentier",
  "Est-ce que ton grand-père est charpentier?",
  "Ma grand-mère est cuisinière",
  "Elle n'est pas ma grand-mère",
  "Il est mon neveu",
  "Elle est ma nièce",
  "Est-ce que ta nièce est étudiante?",
  "Ma nièce est étudiante",
  "Mon frère est étudiant",
  "Est-ce que ton frère est étudiant?",
  "Ma sœur n'est pas étudiante",
  "Il est mon cousin",
  "Elle est ma cousine",
  "Est-ce que ta cousine est docteur?",
  "Ma cousine est docteur",
  "Mon oncle est musicien",
  "Est-ce que ton oncle est musicien?",
  "Ma tante est infirmière",
  "Elle n'est pas ma tante",
  "Il est mon beau-frère",
  "Elle est ma belle-sœur",
  "Est-ce que ton beau-frère est maître?",
  "Mon beau-frère est maître",
  "Ma belle-sœur est boulangère",
  "Est-ce que ta belle-sœur est boulangère?",
  "Mon père n'est pas charpentier",
  "Ma mère n'est pas cuisinière",
  "Est-ce que ton père est docteur?",
  "Est-ce que ta mère est infirmière?",
  "Mon ami est étudiant",
  "Ma amie est étudiante",
  "Est-ce que ton ami est musicien?",
  "Est-ce que ta amie est docteur?",
  "Mon grand-père n'est pas vendeur",
  "Ma grand-mère n'est pas maîtresse",
  "Il est mon mari",
  "Elle est ma femme",
  "Est-ce que ta femme est docteur?",
  "Est-ce que ton mari est maître?",
  "Mon mari est charpentier",
  "Ma femme est cuisinière",
  "Mon frère est docteur",
  "Ma sœur est infirmière",
  "Est-ce que ton frère est docteur?",
  "Est-ce que ta sœur est infirmière?",
  "Mon cousin n'est pas musicien",
  "Ma cousine n'est pas docteur",
  "Il est mon voisin",
  "Elle est ma voisine",
  "Est-ce que ton voisin est boulanger?",
  "Est-ce que ta voisine est maîtresse?",
  "Mon voisin est boulanger",
  "Ma voisine est maîtresse",
  "Mon neveu est musicien",
  "Ma nièce est docteur",
  "Est-ce que ton neveu est musicien?",
  "Est-ce que ta nièce est docteur?",
  "Mon oncle n'est pas charpentier",
  "Ma tante n'est pas cuisinière",
  "Il est mon professeur",
  "Elle est ma professeure",
  "Est-ce que ton professeur est musicien?",
  "Est-ce que ta professeure est docteur?",
  "Mon professeur est musicien",
  "Ma professeure est docteur",
  "Mon père est musicien",
  "Ma mère est maîtresse",
  "Est-ce que ton père est musicien?",
  "Est-ce que ta mère est maîtresse?",
  "Mon grand-père est docteur",
  "Ma grand-mère est infirmière",
  "Est-ce que ton grand-père est docteur?",
  "Est-ce que ta grand-mère est infirmière?",
  "Mon ami n'est pas charpentier",
  "Ma amie n'est pas cuisinière",
  "Il est mon chef",
  "Elle est ma patronne"
];

export const phrases_PT = [
  "Ele é meu pai, Max",
  "Ela é minha irmã",
  "Ele não é meu marido",
  "Essa é sua avó?",
  "Meu irmão é padeiro",
  "Seu irmão é padeiro?",
  "Minha irmã é professora",
  "Não, meu irmão não é carpinteiro",
  "Ele é meu tio",
  "Ela é minha tia",
  "Seu primo é músico?",
  "Meu primo é músico",
  "Minha mãe é médica",
  "Sua mãe é médica?",
  "Meu pai é professor",
  "Não, meu pai não é professor",
  "Ela é minha amiga",
  "Ele é meu amigo",
  "Seu amigo é vendedor?",
  "Meu amigo é vendedor",
  "Meu avô é carpinteiro",
  "Seu avô é carpinteiro?",
  "Minha avó é cozinheira",
  "Ela não é minha avó",
  "Ele é meu sobrinho",
  "Ela é minha sobrinha",
  "Sua sobrinha é estudante?",
  "Minha sobrinha é estudante",
  "Meu irmão é estudante",
  "Seu irmão é estudante?",
  "Minha irmã não é estudante",
  "Ele é meu primo",
  "Ela é minha prima",
  "Sua prima é médica?",
  "Minha prima é médica",
  "Meu tio é músico",
  "Seu tio é músico?",
  "Minha tia é enfermeira",
  "Ela não é minha tia",
  "Ele é meu cunhado",
  "Ela é minha cunhada",
  "Seu cunhado é professor?",
  "Meu cunhado é professor",
  "Minha cunhada é padeira",
  "Sua cunhada é padeira?",
  "Meu pai não é carpinteiro",
  "Minha mãe não é cozinheira",
  "Seu pai é médico?",
  "Sua mãe é enfermeira?",
  "Meu amigo é estudante",
  "Minha amiga é estudante",
  "Seu amigo é músico?",
  "Sua amiga é médica?",
  "Meu avô não é vendedor",
  "Minha avó não é professora",
  "Ele é meu marido",
  "Ela é minha esposa",
  "Sua esposa é médica?",
  "Seu marido é professor?",
  "Meu marido é carpinteiro",
  "Minha esposa é cozinheira",
  "Meu irmão é médico",
  "Minha irmã é enfermeira",
  "Seu irmão é médico?",
  "Sua irmã é enfermeira?",
  "Meu primo não é músico",
  "Minha prima não é médica",
  "Ele é meu vizinho",
  "Ela é minha vizinha",
  "Seu vizinho é padeiro?",
  "Sua vizinha é professora?",
  "Meu vizinho é padeiro",
  "Minha vizinha é professora",
  "Meu sobrinho é músico",
  "Minha sobrinha é médica",
  "Seu sobrinho é músico?",
  "Sua sobrinha é médica?",
  "Meu tio não é carpinteiro",
  "Minha tia não é cozinheira",
  "Ele é meu professor",
  "Ela é minha professora",
  "Seu professor é músico?",
  "Sua professora é médica?",
  "Meu professor é músico",
  "Minha professora é médica",
  "Meu pai é músico",
  "Minha mãe é professora",
  "Seu pai é músico?",
  "Sua mãe é professora?",
  "Meu avô é médico",
  "Minha avó é enfermeira",
  "Seu avô é médico?",
  "Sua avó é enfermeira?",
  "Meu amigo não é carpinteiro",
  "Minha amiga não é cozinheira",
  "Ele é meu chefe",
  "Ela é minha chefe"
];
