export const phrases_ES = [
  "Hola, me llamo Alex",
  "Mi nombre es Max",
  "Ella es Anna",
  "El es David",
  "Estamos en Berlín",
  "Vengo de Londres",
  "¿Dónde está la estación?",
  "El hotel está aquí",
  "El café está allá",
  "El restaurante es grande",
  "El parque es pequeño",
  "La biblioteca está a la izquierda",
  "El hotel está a la derecha",
  "París es una ciudad bonita",
  "Tokio es una ciudad grande",
  "Toronto está en Canadá",
  "Berlín es interesante",
  "¿Vienes de Londres?",
  "Sí, vengo de Londres",
  "No, no vengo de París",
  "Mi hermano es panadero",
  "Mi hermana es panadera",
  "Mi mamá es profesora",
  "Mi papá es profesor",
  "Mi hijo está en la escuela",
  "Mi hija está en casa",
  "El hombre es amable",
  "La mujer es amable",
  "El vendedor es gracioso",
  "El profesor es bueno",
  "La profesora es amable",
  "¿Eres mi hermano?",
  "Sí, soy tu hermano",
  "No, no soy tu hermana",
  "¿Dónde está la panadería?",
  "La panadería está aquí",
  "El pan está fresco",
  "El queso es rico",
  "La pizza es rica",
  "El schnitzel es barato",
  "La salchicha es buena",
  "El café está caliente",
  "El té está frío",
  "El agua está aquí",
  "La leche está allá",
  "El azúcar está sobre la mesa",
  "Las galletas son dulces",
  "La ensalada está fresca",
  "¿Quieres pan con queso?",
  "Sí, quiero pan con queso",
  "No, no quiero pizza",
  "Tengo hambre",
  "Estoy lleno",
  "¿Tienes hambre?",
  "Sí, tengo hambre",
  "No, no estoy lleno",
  "El hotel es caro",
  "El café es barato",
  "El restaurante es bonito",
  "La ciudad es grande",
  "La ciudad no es pequeña",
  "¿Dónde está el metro?",
  "El metro está allá",
  "¿Dónde está el parque?",
  "El parque está aquí",
  "¿Dónde está el hotel?",
  "El hotel está a la izquierda",
  "El restaurante está a la derecha",
  "¿Es grande la biblioteca?",
  "Sí, la biblioteca es grande",
  "No, la biblioteca no es pequeña",
  "¿Está fresco el pan?",
  "Sí, el pan está fresco",
  "No, el pan no es barato",
  "¿Es bueno el queso?",
  "Sí, el queso es bueno",
  "No, el queso no es malo",
  "¿Es amable el hombre?",
  "Sí, el hombre es amable",
  "No, el hombre no es amable",
  "¿Es amable la mujer?",
  "Sí, la mujer es amable",
  "No, la mujer no es mala",
  "¿Es gracioso el profesor?",
  "Sí, el profesor es gracioso",
  "No, el profesor no es aburrido",
  "¿Es amable la profesora?",
  "Sí, la profesora es amable",
  "No, la profesora no es mala",
  "¿Es barato el café?",
  "Sí, el café es barato",
  "No, el café no es caro",
  "¿Es bonita la ciudad?",
  "Sí, la ciudad es bonita",
  "No, la ciudad no es fea",
  "¿Es grande el hotel?",
  "Sí, el hotel es grande",
  "No, el hotel no es pequeño",
  "¿Es bueno el restaurante?",
  "Sí, el restaurante es bueno",
  "¿Dónde está el metro?",
  "El metro está aquí",
  "El parque está allá",
  "El hotel no es barato",
  "El café no es caro",
  "El restaurante no es grande",
  "La biblioteca no es pequeña",
  "El pan no está fresco",
  "El queso no es bueno",
  "La pizza no es rica",
  "El schnitzel no es barato",
  "La salchicha no es buena",
  "El café no está caliente",
  "El té no está frío",
  "El agua no está aquí",
  "La leche no está allá",
  "El azúcar no está sobre la mesa",
  "Las galletas no son dulces",
  "La ensalada no está fresca",
  "¿Quieres agua con azúcar?",
  "Sí, quiero agua con azúcar",
  "No, no quiero leche",
  "Estoy cansado",
  "Estoy feliz",
  "Estoy triste",
  "¿Estás cansado?",
  "Sí, estoy cansado",
  "No, no estoy feliz",
  "¿Estás triste?",
  "Sí, estoy triste",
  "No, no estoy cansado",
  "¿Dónde está tu hermano?",
  "Mi hermano está en el café",
  "¿Dónde está tu hermana?",
  "Mi hermana está en la biblioteca",
  "¿Dónde está tu mamá?",
  "Mi mamá está en el hotel",
  "¿Dónde está tu papá?",
  "Mi papá está en el parque",
  "¿Dónde está tu hijo?",
  "Mi hijo está en la escuela",
  "¿Dónde está tu hija?",
  "Mi hija está en casa",
  "¿Dónde está el hombre?",
  "El hombre está en el restaurante",
  "¿Dónde está la mujer?",
  "La mujer está en el café",
  "¿Dónde está el profesor?",
  "El profesor está en la escuela",
  "¿Dónde está la profesora?",
  "La profesora está en la biblioteca",
  "¿Dónde está el vendedor?",
  "El vendedor está en la panadería",
  "¿Dónde está el panadero?",
  "El panadero está en la panadería",
  "¿Dónde está la panadera?",
  "La panadera está en la panadería",
  "¿Dónde está el hotel?",
  "El hotel está en la ciudad",
  "¿Dónde está el restaurante?",
  "El restaurante está en la ciudad",
  "¿Dónde está el café?",
  "El café está en la ciudad",
  "¿Dónde está la biblioteca?",
  "La biblioteca está en la ciudad",
  "¿Dónde está el parque?",
  "El parque está en la ciudad",
  "¿Dónde está la estación?",
  "La estación está en la ciudad",
  "¿Dónde está el metro?",
  "El metro está en la ciudad",
  "¿Es grande la ciudad?",
  "Sí, la ciudad es grande",
  "No, la ciudad no es pequeña",
  "¿Es bonito el parque?",
  "Sí, el parque es bonito",
  "No, el parque no es feo",
  "¿Es barato el hotel?",
  "Sí, el hotel es barato",
  "No, el hotel no es caro",
  "¿Es caro el restaurante?",
  "Sí, el restaurante es caro",
  "No, el restaurante no es barato",
  "¿Es bueno el café?",
  "Sí, el café es bueno",
  "No, el café no es malo",
  "¿Está fresca la ensalada?",
  "Sí, la ensalada está fresca",
  "No, la ensalada no está vieja",
  "¿Es dulce el azúcar?",
  "Sí, el azúcar es dulce",
  "No, el azúcar no es salado",
  "¿Es rica la pizza?",
  "Sí, la pizza es rica",
  "No, la pizza no es mala",
  "¿Es rico el queso?",
  "Sí, el queso es rico",
  "No, el queso no es malo",
  "¿Está fresco el pan?",
  "Sí, el pan está fresco"
];

export const phrases_EN = [
  "Hello, my name is Alex",
  "My name is Max",
  "She is Anna",
  "He is David",
  "We are in Berlin",
  "I come from London",
  "Where is the station?",
  "The hotel is here",
  "The café is over there",
  "The restaurant is big",
  "The park is small",
  "The library is on the left",
  "The hotel is on the right",
  "Paris is a beautiful city",
  "Tokyo is a big city",
  "Toronto is in Canada",
  "Berlin is interesting",
  "Do you come from London?",
  "Yes, I come from London",
  "No, I don’t come from Paris",
  "My brother is a baker",
  "My sister is a baker",
  "My mom is a teacher",
  "My dad is a teacher",
  "My son is at school",
  "My daughter is at home",
  "The man is kind",
  "The woman is kind",
  "The salesman is funny",
  "The teacher is good",
  "The female teacher is kind",
  "Are you my brother?",
  "Yes, I am your brother",
  "No, I am not your sister",
  "Where is the bakery?",
  "The bakery is here",
  "The bread is fresh",
  "The cheese is tasty",
  "The pizza is tasty",
  "The schnitzel is cheap",
  "The sausage is good",
  "The coffee is hot",
  "The tea is cold",
  "The water is here",
  "The milk is over there",
  "The sugar is on the table",
  "The cookies are sweet",
  "The salad is fresh",
  "Do you want bread with cheese?",
  "Yes, I want bread with cheese",
  "No, I don’t want pizza",
  "I am hungry",
  "I am full",
  "Are you hungry?",
  "Yes, I am hungry",
  "No, I am not full",
  "The hotel is expensive",
  "The coffee is cheap",
  "The restaurant is nice",
  "The city is big",
  "The city is not small",
  "Where is the subway?",
  "The subway is over there",
  "Where is the park?",
  "The park is here",
  "Where is the hotel?",
  "The hotel is on the left",
  "The restaurant is on the right",
  "Is the library big?",
  "Yes, the library is big",
  "No, the library is not small",
  "Is the bread fresh?",
  "Yes, the bread is fresh",
  "No, the bread is not cheap",
  "Is the cheese good?",
  "Yes, the cheese is good",
  "No, the cheese is not bad",
  "Is the man kind?",
  "Yes, the man is kind",
  "No, the man is not kind",
  "Is the woman kind?",
  "Yes, the woman is kind",
  "No, the woman is not bad",
  "Is the teacher funny?",
  "Yes, the teacher is funny",
  "No, the teacher is not boring",
  "Is the female teacher kind?",
  "Yes, the female teacher is kind",
  "No, the female teacher is not bad",
  "Is the coffee cheap?",
  "Yes, the coffee is cheap",
  "No, the coffee is not expensive",
  "Is the city beautiful?",
  "Yes, the city is beautiful",
  "No, the city is not ugly",
  "Is the hotel big?",
  "Yes, the hotel is big",
  "No, the hotel is not small",
  "Is the restaurant good?",
  "Yes, the restaurant is good",
  "Where is the subway?",
  "The subway is here",
  "The park is over there",
  "The hotel is not cheap",
  "The coffee is not expensive",
  "The restaurant is not big",
  "The library is not small",
  "The bread is not fresh",
  "The cheese is not good",
  "The pizza is not tasty",
  "The schnitzel is not cheap",
  "The sausage is not good",
  "The coffee is not hot",
  "The tea is not cold",
  "The water is not here",
  "The milk is not over there",
  "The sugar is not on the table",
  "The cookies are not sweet",
  "The salad is not fresh",
  "Do you want water with sugar?",
  "Yes, I want water with sugar",
  "No, I don’t want milk",
  "I am tired",
  "I am happy",
  "I am sad",
  "Are you tired?",
  "Yes, I am tired",
  "No, I am not happy",
  "Are you sad?",
  "Yes, I am sad",
  "No, I am not tired",
  "Where is your brother?",
  "My brother is at the café",
  "Where is your sister?",
  "My sister is at the library",
  "Where is your mom?",
  "My mom is at the hotel",
  "Where is your dad?",
  "My dad is at the park",
  "Where is your son?",
  "My son is at school",
  "Where is your daughter?",
  "My daughter is at home",
  "Where is the man?",
  "The man is at the restaurant",
  "Where is the woman?",
  "The woman is at the café",
  "Where is the teacher?",
  "The teacher is at school",
  "Where is the female teacher?",
  "The female teacher is at the library",
  "Where is the salesman?",
  "The salesman is at the bakery",
  "Where is the baker?",
  "The baker is at the bakery",
  "Where is the female baker?",
  "The female baker is at the bakery",
  "Where is the hotel?",
  "The hotel is in the city",
  "Where is the restaurant?",
  "The restaurant is in the city",
  "Where is the café?",
  "The café is in the city",
  "Where is the library?",
  "The library is in the city",
  "Where is the park?",
  "The park is in the city",
  "Where is the station?",
  "The station is in the city",
  "Where is the subway?",
  "The subway is in the city",
  "Is the city big?",
  "Yes, the city is big",
  "No, the city is not small",
  "Is the park nice?",
  "Yes, the park is nice",
  "No, the park is not ugly",
  "Is the hotel cheap?",
  "Yes, the hotel is cheap",
  "No, the hotel is not expensive",
  "Is the restaurant expensive?",
  "Yes, the restaurant is expensive",
  "No, the restaurant is not cheap",
  "Is the coffee good?",
  "Yes, the coffee is good",
  "No, the coffee is not bad",
  "Is the salad fresh?",
  "Yes, the salad is fresh",
  "No, the salad is not old",
  "Is the sugar sweet?",
  "Yes, the sugar is sweet",
  "No, the sugar is not salty",
  "Is the pizza tasty?",
  "Yes, the pizza is tasty",
  "No, the pizza is not bad",
  "Is the cheese tasty?",
  "Yes, the cheese is tasty",
  "No, the cheese is not bad",
  "Is the bread fresh?",
  "Yes, the bread is fresh"
];

export const phrases_DE = [
  "Hallo, ich heiße Alex",
  "Mein Name ist Max",
  "Sie ist Anna",
  "Er ist David",
  "Wir sind in Berlin",
  "Ich komme aus London",
  "Wo ist der Bahnhof?",
  "Das Hotel ist hier",
  "Das Café ist da drüben",
  "Das Restaurant ist groß",
  "Der Park ist klein",
  "Die Bibliothek ist links",
  "Das Hotel ist rechts",
  "Paris ist eine schöne Stadt",
  "Tokio ist eine große Stadt",
  "Toronto ist in Kanada",
  "Berlin ist interessant",
  "Kommst du aus London?",
  "Ja, ich komme aus London",
  "Nein, ich komme nicht aus Paris",
  "Mein Bruder ist Bäcker",
  "Meine Schwester ist Bäckerin",
  "Meine Mama ist Lehrerin",
  "Mein Papa ist Lehrer",
  "Mein Sohn ist in der Schule",
  "Meine Tochter ist zu Hause",
  "Der Mann ist nett",
  "Die Frau ist nett",
  "Der Verkäufer ist lustig",
  "Der Lehrer ist gut",
  "Die Lehrerin ist nett",
  "Bist du mein Bruder?",
  "Ja, ich bin dein Bruder",
  "Nein, ich bin nicht deine Schwester",
  "Wo ist die Bäckerei?",
  "Die Bäckerei ist hier",
  "Das Brot ist frisch",
  "Der Käse ist lecker",
  "Die Pizza ist lecker",
  "Das Schnitzel ist billig",
  "Die Wurst ist gut",
  "Der Kaffee ist heiß",
  "Der Tee ist kalt",
  "Das Wasser ist hier",
  "Die Milch ist da drüben",
  "Der Zucker ist auf dem Tisch",
  "Die Kekse sind süß",
  "Der Salat ist frisch",
  "Willst du Brot mit Käse?",
  "Ja, ich will Brot mit Käse",
  "Nein, ich will keine Pizza",
  "Ich bin hungrig",
  "Ich bin satt",
  "Bist du hungrig?",
  "Ja, ich bin hungrig",
  "Nein, ich bin nicht satt",
  "Das Hotel ist teuer",
  "Das Café ist billig",
  "Das Restaurant ist schön",
  "Die Stadt ist groß",
  "Die Stadt ist nicht klein",
  "Wo ist die U-Bahn?",
  "Die U-Bahn ist da drüben",
  "Wo ist der Park?",
  "Der Park ist hier",
  "Wo ist das Hotel?",
  "Das Hotel ist links",
  "Das Restaurant ist rechts",
  "Ist die Bibliothek groß?",
  "Ja, die Bibliothek ist groß",
  "Nein, die Bibliothek ist nicht klein",
  "Ist das Brot frisch?",
  "Ja, das Brot ist frisch",
  "Nein, das Brot ist nicht billig",
  "Ist der Käse gut?",
  "Ja, der Käse ist gut",
  "Nein, der Käse ist nicht schlecht",
  "Ist der Mann nett?",
  "Ja, der Mann ist nett",
  "Nein, der Mann ist nicht nett",
  "Ist die Frau nett?",
  "Ja, die Frau ist nett",
  "Nein, die Frau ist nicht schlecht",
  "Ist der Lehrer lustig?",
  "Ja, der Lehrer ist lustig",
  "Nein, der Lehrer ist nicht langweilig",
  "Ist die Lehrerin nett?",
  "Ja, die Lehrerin ist nett",
  "Nein, die Lehrerin ist nicht schlecht",
  "Ist der Kaffee billig?",
  "Ja, der Kaffee ist billig",
  "Nein, der Kaffee ist nicht teuer",
  "Ist die Stadt schön?",
  "Ja, die Stadt ist schön",
  "Nein, die Stadt ist nicht hässlich",
  "Ist das Hotel groß?",
  "Ja, das Hotel ist groß",
  "Nein, das Hotel ist nicht klein",
  "Ist das Restaurant gut?",
  "Ja, das Restaurant ist gut",
  "Wo ist die U-Bahn?",
  "Die U-Bahn ist hier",
  "Der Park ist da drüben",
  "Das Hotel ist nicht billig",
  "Das Café ist nicht teuer",
  "Das Restaurant ist nicht groß",
  "Die Bibliothek ist nicht klein",
  "Das Brot ist nicht frisch",
  "Der Käse ist nicht gut",
  "Die Pizza ist nicht lecker",
  "Das Schnitzel ist nicht billig",
  "Die Wurst ist nicht gut",
  "Der Kaffee ist nicht heiß",
  "Der Tee ist nicht kalt",
  "Das Wasser ist nicht hier",
  "Die Milch ist nicht da drüben",
  "Der Zucker ist nicht auf dem Tisch",
  "Die Kekse sind nicht süß",
  "Der Salat ist nicht frisch",
  "Willst du Wasser mit Zucker?",
  "Ja, ich will Wasser mit Zucker",
  "Nein, ich will keine Milch",
  "Ich bin müde",
  "Ich bin glücklich",
  "Ich bin traurig",
  "Bist du müde?",
  "Ja, ich bin müde",
  "Nein, ich bin nicht glücklich",
  "Bist du traurig?",
  "Ja, ich bin traurig",
  "Nein, ich bin nicht müde",
  "Wo ist dein Bruder?",
  "Mein Bruder ist im Café",
  "Wo ist deine Schwester?",
  "Meine Schwester ist in der Bibliothek",
  "Wo ist deine Mama?",
  "Meine Mama ist im Hotel",
  "Wo ist dein Papa?",
  "Mein Papa ist im Park",
  "Wo ist dein Sohn?",
  "Mein Sohn ist in der Schule",
  "Wo ist deine Tochter?",
  "Meine Tochter ist zu Hause",
  "Wo ist der Mann?",
  "Der Mann ist im Restaurant",
  "Wo ist die Frau?",
  "Die Frau ist im Café",
  "Wo ist der Lehrer?",
  "Der Lehrer ist in der Schule",
  "Wo ist die Lehrerin?",
  "Die Lehrerin ist in der Bibliothek",
  "Wo ist der Verkäufer?",
  "Der Verkäufer ist in der Bäckerei",
  "Wo ist der Bäcker?",
  "Der Bäcker ist in der Bäckerei",
  "Wo ist die Bäckerin?",
  "Die Bäckerin ist in der Bäckerei",
  "Wo ist das Hotel?",
  "Das Hotel ist in der Stadt",
  "Wo ist das Restaurant?",
  "Das Restaurant ist in der Stadt",
  "Wo ist das Café?",
  "Das Café ist in der Stadt",
  "Wo ist die Bibliothek?",
  "Die Bibliothek ist in der Stadt",
  "Wo ist der Park?",
  "Der Park ist in der Stadt",
  "Wo ist der Bahnhof?",
  "Der Bahnhof ist in der Stadt",
  "Wo ist die U-Bahn?",
  "Die U-Bahn ist in der Stadt",
  "Ist die Stadt groß?",
  "Ja, die Stadt ist groß",
  "Nein, die Stadt ist nicht klein",
  "Ist der Park schön?",
  "Ja, der Park ist schön",
  "Nein, der Park ist nicht hässlich",
  "Ist das Hotel billig?",
  "Ja, das Hotel ist billig",
  "Nein, das Hotel ist nicht teuer",
  "Ist das Restaurant teuer?",
  "Ja, das Restaurant ist teuer",
  "Nein, das Restaurant ist nicht billig",
  "Ist das Café gut?",
  "Ja, das Café ist gut",
  "Nein, das Café ist nicht schlecht",
  "Ist der Salat frisch?",
  "Ja, der Salat ist frisch",
  "Nein, der Salat ist nicht alt",
  "Ist der Zucker süß?",
  "Ja, der Zucker ist süß",
  "Nein, der Zucker ist nicht salzig",
  "Ist die Pizza lecker?",
  "Ja, die Pizza ist lecker",
  "Nein, die Pizza ist nicht schlecht",
  "Ist der Käse lecker?",
  "Ja, der Käse ist lecker",
  "Nein, der Käse ist nicht schlecht",
  "Ist das Brot frisch?",
  "Ja, das Brot ist frisch"
];

export const phrases_IT = [
  "Ciao, mi chiamo Alex",
  "Il mio nome è Max",
  "Lei è Anna",
  "Lui è David",
  "Siamo a Berlino",
  "Vengo da Londra",
  "Dove si trova la stazione?",
  "L'hotel è qui",
  "Il caffè è là",
  "Il ristorante è grande",
  "Il parco è piccolo",
  "La biblioteca è a sinistra",
  "L'hotel è a destra",
  "Parigi è una città bella",
  "Tokyo è una città grande",
  "Toronto è in Canada",
  "Berlino è interessante",
  "Vieni da Londra?",
  "Sì, vengo da Londra",
  "No, non vengo da Parigi",
  "Mio fratello è panettiere",
  "Mia sorella è panettiera",
  "Mia mamma è insegnante",
  "Mio papà è insegnante",
  "Mio figlio è a scuola",
  "Mia figlia è a casa",
  "L'uomo è gentile",
  "La donna è gentile",
  "Il venditore è divertente",
  "Il professore è bravo",
  "La professoressa è gentile",
  "Sei mio fratello?",
  "Sì, sono tuo fratello",
  "No, non sono tua sorella",
  "Dove si trova la panetteria?",
  "La panetteria è qui",
  "Il pane è fresco",
  "Il formaggio è buono",
  "La pizza è buona",
  "Lo schnitzel è economico",
  "La salsiccia è buona",
  "Il caffè è caldo",
  "Il tè è freddo",
  "L'acqua è qui",
  "Il latte è là",
  "Lo zucchero è sul tavolo",
  "I biscotti sono dolci",
  "L'insalata è fresca",
  "Vuoi pane con formaggio?",
  "Sì, voglio pane con formaggio",
  "No, non voglio pizza",
  "Ho fame",
  "Sono pieno",
  "Hai fame?",
  "Sì, ho fame",
  "No, non sono pieno",
  "L'hotel è caro",
  "Il caffè è economico",
  "Il ristorante è bello",
  "La città è grande",
  "La città non è piccola",
  "Dove si trova la metropolitana?",
  "La metropolitana è là",
  "Dove si trova il parco?",
  "Il parco è qui",
  "Dove si trova l'hotel?",
  "L'hotel è a sinistra",
  "Il ristorante è a destra",
  "È grande la biblioteca?",
  "Sì, la biblioteca è grande",
  "No, la biblioteca non è piccola",
  "È fresco il pane?",
  "Sì, il pane è fresco",
  "No, il pane non è economico",
  "È buono il formaggio?",
  "Sì, il formaggio è buono",
  "No, il formaggio non è cattivo",
  "È gentile l'uomo?",
  "Sì, l'uomo è gentile",
  "No, l'uomo non è gentile",
  "È gentile la donna?",
  "Sì, la donna è gentile",
  "No, la donna non è cattiva",
  "È divertente il professore?",
  "Sì, il professore è divertente",
  "No, il professore non è noioso",
  "È gentile la professoressa?",
  "Sì, la professoressa è gentile",
  "No, la professoressa non è cattiva",
  "È economico il caffè?",
  "Sì, il caffè è economico",
  "No, il caffè non è caro",
  "È bella la città?",
  "Sì, la città è bella",
  "No, la città non è brutta",
  "È grande l'hotel?",
  "Sì, l'hotel è grande",
  "No, l'hotel non è piccolo",
  "È buono il ristorante?",
  "Sì, il ristorante è buono",
  "Dove si trova la metropolitana?",
  "La metropolitana è qui",
  "Il parco è là",
  "L'hotel non è economico",
  "Il caffè non è caro",
  "Il ristorante non è grande",
  "La biblioteca non è piccola",
  "Il pane non è fresco",
  "Il formaggio non è buono",
  "La pizza non è buona",
  "Lo schnitzel non è economico",
  "La salsiccia non è buona",
  "Il caffè non è caldo",
  "Il tè non è freddo",
  "L'acqua non è qui",
  "Il latte non è là",
  "Lo zucchero non è sul tavolo",
  "I biscotti non sono dolci",
  "L'insalata non è fresca",
  "Vuoi acqua con zucchero?",
  "Sì, voglio acqua con zucchero",
  "No, non voglio latte",
  "Sono stanco",
  "Sono felice",
  "Sono triste",
  "Sei stanco?",
  "Sì, sono stanco",
  "No, non sono felice",
  "Sei triste?",
  "Sì, sono triste",
  "No, non sono stanco",
  "Dove si trova tuo fratello?",
  "Mio fratello è al caffè",
  "Dove si trova tua sorella?",
  "Mia sorella è in biblioteca",
  "Dove si trova tua mamma?",
  "Mia mamma è all'hotel",
  "Dove si trova tuo papà?",
  "Mio papà è al parco",
  "Dove si trova tuo figlio?",
  "Mio figlio è a scuola",
  "Dove si trova tua figlia?",
  "Mia figlia è a casa",
  "Dove si trova l'uomo?",
  "L'uomo è al ristorante",
  "Dove si trova la donna?",
  "La donna è al caffè",
  "Dove si trova il professore?",
  "Il professore è a scuola",
  "Dove si trova la professoressa?",
  "La professoressa è in biblioteca",
  "Dove si trova il venditore?",
  "Il venditore è in panetteria",
  "Dove si trova il panettiere?",
  "Il panettiere è in panetteria",
  "Dove si trova la panettiera?",
  "La panettiera è in panetteria",
  "Dove si trova l'hotel?",
  "L'hotel è in città",
  "Dove si trova il ristorante?",
  "Il ristorante è in città",
  "Dove si trova il caffè?",
  "Il caffè è in città",
  "Dove si trova la biblioteca?",
  "La biblioteca è in città",
  "Dove si trova il parco?",
  "Il parco è in città",
  "Dove si trova la stazione?",
  "La stazione è in città",
  "Dove si trova la metropolitana?",
  "La metropolitana è in città",
  "È grande la città?",
  "Sì, la città è grande",
  "No, la città non è piccola",
  "È bello il parco?",
  "Sì, il parco è bello",
  "No, il parco non è brutto",
  "È economico l'hotel?",
  "Sì, l'hotel è economico",
  "No, l'hotel non è caro",
  "È caro il ristorante?",
  "Sì, il ristorante è caro",
  "No, il ristorante non è economico",
  "È buono il caffè?",
  "Sì, il caffè è buono",
  "No, il caffè non è cattivo",
  "È fresca l'insalata?",
  "Sì, l'insalata è fresca",
  "No, l'insalata non è vecchia",
  "È dolce lo zucchero?",
  "Sì, lo zucchero è dolce",
  "No, lo zucchero non è salato",
  "È buona la pizza?",
  "Sì, la pizza è buona",
  "No, la pizza non è cattiva",
  "È buono il formaggio?",
  "Sì, il formaggio è buono",
  "No, il formaggio non è cattivo",
  "È fresco il pane?",
  "Sì, il pane è fresco"
];

export const phrases_FR = [
  "Bonjour, je m'appelle Alex",
  "Mon nom est Max",
  "Elle s'appelle Anna",
  "Il s'appelle David",
  "Nous sommes à Berlin",
  "Je viens de Londres",
  "Où est la gare?",
  "L'hôtel est ici",
  "Le café est là-bas",
  "Le restaurant est grand",
  "Le parc est petit",
  "La bibliothèque est à gauche",
  "L'hôtel est à droite",
  "Paris est une belle ville",
  "Tokyo est une grande ville",
  "Toronto est au Canada",
  "Berlin est intéressante",
  "Viens-tu de Londres?",
  "Oui, je viens de Londres",
  "Non, je ne viens pas de Paris",
  "Mon frère est boulanger",
  "Ma sœur est boulangère",
  "Ma mère est professeure",
  "Mon père est professeur",
  "Mon fils est à l'école",
  "Ma fille est à la maison",
  "L'homme est gentil",
  "La femme est gentille",
  "Le vendeur est amusant",
  "Le professeur est bon",
  "La professeure est gentille",
  "Es-tu mon frère?",
  "Oui, je suis ton frère",
  "Non, je ne suis pas ta sœur",
  "Où est la boulangerie?",
  "La boulangerie est ici",
  "Le pain est frais",
  "Le fromage est délicieux",
  "La pizza est délicieuse",
  "La schnitzel est bon marché",
  "La saucisse est bonne",
  "Le café est chaud",
  "Le thé est froid",
  "L'eau est ici",
  "Le lait est là-bas",
  "Le sucre est sur la table",
  "Les biscuits sont sucrés",
  "La salade est fraîche",
  "Veux-tu du pain avec du fromage?",
  "Oui, je veux du pain avec du fromage",
  "Non, je ne veux pas de pizza",
  "J'ai faim",
  "Je suis rassasié",
  "As-tu faim?",
  "Oui, j'ai faim",
  "Non, je ne suis pas rassasié",
  "L'hôtel est cher",
  "Le café est bon marché",
  "Le restaurant est joli",
  "La ville est grande",
  "La ville n'est pas petite",
  "Où est le métro?",
  "Le métro est là-bas",
  "Où est le parc?",
  "Le parc est ici",
  "Où est l'hôtel?",
  "L'hôtel est à gauche",
  "Le restaurant est à droite",
  "La bibliothèque est-elle grande?",
  "Oui, la bibliothèque est grande",
  "Non, la bibliothèque n'est pas petite",
  "Le pain est-il frais?",
  "Oui, le pain est frais",
  "Non, le pain n'est pas bon marché",
  "Le fromage est-il bon?",
  "Oui, le fromage est bon",
  "Non, le fromage n'est pas mauvais",
  "L'homme est-il gentil?",
  "Oui, l'homme est gentil",
  "Non, l'homme n'est pas gentil",
  "La femme est-elle gentille?",
  "Oui, la femme est gentille",
  "Non, la femme n'est pas méchante",
  "Le professeur est-il amusant?",
  "Oui, le professeur est amusant",
  "Non, le professeur n'est pas ennuyeux",
  "La professeure est-elle gentille?",
  "Oui, la professeure est gentille",
  "Non, la professeure n'est pas méchante",
  "Le café est-il bon marché?",
  "Oui, le café est bon marché",
  "Non, le café n'est pas cher",
  "La ville est-elle belle?",
  "Oui, la ville est belle",
  "Non, la ville n'est pas laide",
  "L'hôtel est-il grand?",
  "Oui, l'hôtel est grand",
  "Non, l'hôtel n'est pas petit",
  "Le restaurant est-il bon?",
  "Oui, le restaurant est bon",
  "Où est le métro?",
  "Le métro est ici",
  "Le parc est là-bas",
  "L'hôtel n'est pas bon marché",
  "Le café n'est pas cher",
  "Le restaurant n'est pas grand",
  "La bibliothèque n'est pas petite",
  "Le pain n'est pas frais",
  "Le fromage n'est pas bon",
  "La pizza n'est pas délicieuse",
  "La schnitzel n'est pas bon marché",
  "La saucisse n'est pas bonne",
  "Le café n'est pas chaud",
  "Le thé n'est pas froid",
  "L'eau n'est pas ici",
  "Le lait n'est pas là-bas",
  "Le sucre n'est pas sur la table",
  "Les biscuits ne sont pas sucrés",
  "La salade n'est pas fraîche",
  "Veux-tu de l'eau avec du sucre?",
  "Oui, je veux de l'eau avec du sucre",
  "Non, je ne veux pas de lait",
  "Je suis fatigué",
  "Je suis heureux",
  "Je suis triste",
  "Es-tu fatigué?",
  "Oui, je suis fatigué",
  "Non, je ne suis pas heureux",
  "Es-tu triste?",
  "Oui, je suis triste",
  "Non, je ne suis pas fatigué",
  "Où est ton frère?",
  "Mon frère est au café",
  "Où est ta sœur?",
  "Ma sœur est à la bibliothèque",
  "Où est ta mère?",
  "Ma mère est à l'hôtel",
  "Où est ton père?",
  "Mon père est au parc",
  "Où est ton fils?",
  "Mon fils est à l'école",
  "Où est ta fille?",
  "Ma fille est à la maison",
  "Où est l'homme?",
  "L'homme est au restaurant",
  "Où est la femme?",
  "La femme est au café",
  "Où est le professeur?",
  "Le professeur est à l'école",
  "Où est la professeure?",
  "La professeure est à la bibliothèque",
  "Où est le vendeur?",
  "Le vendeur est à la boulangerie",
  "Où est le boulanger?",
  "Le boulanger est à la boulangerie",
  "Où est la boulangère?",
  "La boulangère est à la boulangerie",
  "Où est l'hôtel?",
  "L'hôtel est dans la ville",
  "Où est le restaurant?",
  "Le restaurant est dans la ville",
  "Où est le café?",
  "Le café est dans la ville",
  "Où est la bibliothèque?",
  "La bibliothèque est dans la ville",
  "Où est le parc?",
  "Le parc est dans la ville",
  "Où est la gare?",
  "La gare est dans la ville",
  "Où est le métro?",
  "Le métro est dans la ville",
  "La ville est-elle grande?",
  "Oui, la ville est grande",
  "Non, la ville n'est pas petite",
  "Le parc est-il beau?",
  "Oui, le parc est beau",
  "Non, le parc n'est pas laid",
  "L'hôtel est-il bon marché?",
  "Oui, l'hôtel est bon marché",
  "Non, l'hôtel n'est pas cher",
  "Le restaurant est-il cher?",
  "Oui, le restaurant est cher",
  "Non, le restaurant n'est pas bon marché",
  "Le café est-il bon?",
  "Oui, le café est bon",
  "Non, le café n'est pas mauvais",
  "La salade est-elle fraîche?",
  "Oui, la salade est fraîche",
  "Non, la salade n'est pas vieille",
  "Le sucre est-il sucré?",
  "Oui, le sucre est sucré",
  "Non, le sucre n'est pas salé",
  "La pizza est-elle délicieuse?",
  "Oui, la pizza est délicieuse",
  "Non, la pizza n'est pas mauvaise",
  "Le fromage est-il délicieux?",
  "Oui, le fromage est délicieux",
  "Non, le fromage n'est pas mauvais",
  "Le pain est-il frais?",
  "Oui, le pain est frais"
];

export const phrases_PT = [
  "Olá, meu nome é Alex",
  "Meu nome é Max",
  "Ela é Anna",
  "Ele é David",
  "Estamos em Berlim",
  "Venho de Londres",
  "Onde está a estação?",
  "O hotel está aqui",
  "O café está lá",
  "O restaurante é grande",
  "O parque é pequeno",
  "A biblioteca está à esquerda",
  "O hotel está à direita",
  "Paris é uma cidade bonita",
  "Tóquio é uma cidade grande",
  "Toronto está no Canadá",
  "Berlim é interessante",
  "Você vem de Londres?",
  "Sim, venho de Londres",
  "Não, não venho de Paris",
  "Meu irmão é padeiro",
  "Minha irmã é padeira",
  "Minha mãe é professora",
  "Meu pai é professor",
  "Meu filho está na escola",
  "Minha filha está em casa",
  "O homem é gentil",
  "A mulher é gentil",
  "O vendedor é engraçado",
  "O professor é bom",
  "A professora é gentil",
  "Você é meu irmão?",
  "Sim, sou seu irmão",
  "Não, não sou sua irmã",
  "Onde está a padaria?",
  "A padaria está aqui",
  "O pão está fresco",
  "O queijo é saboroso",
  "A pizza é saborosa",
  "O schnitzel é barato",
  "A salsicha é boa",
  "O café está quente",
  "O chá está frio",
  "A água está aqui",
  "O leite está lá",
  "O açúcar está sobre a mesa",
  "Os biscoitos são doces",
  "A salada está fresca",
  "Você quer pão com queijo?",
  "Sim, quero pão com queijo",
  "Não, não quero pizza",
  "Tenho fome",
  "Estou cheio",
  "Você tem fome?",
  "Sim, tenho fome",
  "Não, não estou cheio",
  "O hotel é caro",
  "O café é barato",
  "O restaurante é bonito",
  "A cidade é grande",
  "A cidade não é pequena",
  "Onde está o metrô?",
  "O metrô está lá",
  "Onde está o parque?",
  "O parque está aqui",
  "Onde está o hotel?",
  "O hotel está à esquerda",
  "O restaurante está à direita",
  "A biblioteca é grande?",
  "Sim, a biblioteca é grande",
  "Não, a biblioteca não é pequena",
  "O pão está fresco?",
  "Sim, o pão está fresco",
  "Não, o pão não é barato",
  "O queijo é bom?",
  "Sim, o queijo é bom",
  "Não, o queijo não é ruim",
  "O homem é gentil?",
  "Sim, o homem é gentil",
  "Não, o homem não é gentil",
  "A mulher é gentil?",
  "Sim, a mulher é gentil",
  "Não, a mulher não é má",
  "O professor é engraçado?",
  "Sim, o professor é engraçado",
  "Não, o professor não é chato",
  "A professora é gentil?",
  "Sim, a professora é gentil",
  "Não, a professora não é má",
  "O café é barato?",
  "Sim, o café é barato",
  "Não, o café não é caro",
  "A cidade é bonita?",
  "Sim, a cidade é bonita",
  "Não, a cidade não é feia",
  "O hotel é grande?",
  "Sim, o hotel é grande",
  "Não, o hotel não é pequeno",
  "O restaurante é bom?",
  "Sim, o restaurante é bom",
  "Onde está o metrô?",
  "O metrô está aqui",
  "O parque está lá",
  "O hotel não é barato",
  "O café não é caro",
  "O restaurante não é grande",
  "A biblioteca não é pequena",
  "O pão não está fresco",
  "O queijo não é bom",
  "A pizza não é saborosa",
  "O schnitzel não é barato",
  "A salsicha não é boa",
  "O café não está quente",
  "O chá não está frio",
  "A água não está aqui",
  "O leite não está lá",
  "O açúcar não está sobre a mesa",
  "Os biscoitos não são doces",
  "A salada não está fresca",
  "Você quer água com açúcar?",
  "Sim, quero água com açúcar",
  "Não, não quero leite",
  "Estou cansado",
  "Estou feliz",
  "Estou triste",
  "Você está cansado?",
  "Sim, estou cansado",
  "Não, não estou feliz",
  "Você está triste?",
  "Sim, estou triste",
  "Não, não estou cansado",
  "Onde está seu irmão?",
  "Meu irmão está no café",
  "Onde está sua irmã?",
  "Minha irmã está na biblioteca",
  "Onde está sua mãe?",
  "Minha mãe está no hotel",
  "Onde está seu pai?",
  "Meu pai está no parque",
  "Onde está seu filho?",
  "Meu filho está na escola",
  "Onde está sua filha?",
  "Minha filha está em casa",
  "Onde está o homem?",
  "O homem está no restaurante",
  "Onde está a mulher?",
  "A mulher está no café",
  "Onde está o professor?",
  "O professor está na escola",
  "Onde está a professora?",
  "A professora está na biblioteca",
  "Onde está o vendedor?",
  "O vendedor está na padaria",
  "Onde está o padeiro?",
  "O padeiro está na padaria",
  "Onde está a padeira?",
  "A padeira está na padaria",
  "Onde está o hotel?",
  "O hotel está na cidade",
  "Onde está o restaurante?",
  "O restaurante está na cidade",
  "Onde está o café?",
  "O café está na cidade",
  "Onde está a biblioteca?",
  "A biblioteca está na cidade",
  "Onde está o parque?",
  "O parque está na cidade",
  "Onde está a estação?",
  "A estação está na cidade",
  "Onde está o metrô?",
  "O metrô está na cidade",
  "A cidade é grande?",
  "Sim, a cidade é grande",
  "Não, a cidade não é pequena",
  "O parque é bonito?",
  "Sim, o parque é bonito",
  "Não, o parque não é feio",
  "O hotel é barato?",
  "Sim, o hotel é barato",
  "Não, o hotel não é caro",
  "O restaurante é caro?",
  "Sim, o restaurante é caro",
  "Não, o restaurante não é barato",
  "O café é bom?",
  "Sim, o café é bom",
  "Não, o café não é ruim",
  "A salada está fresca?",
  "Sim, a salada está fresca",
  "Não, a salada não está velha",
  "O açúcar é doce?",
  "Sim, o açúcar é doce",
  "Não, o açúcar não é salgado",
  "A pizza é saborosa?",
  "Sim, a pizza é saborosa",
  "Não, a pizza não é ruim",
  "O queijo é saboroso?",
  "Sim, o queijo é saboroso",
  "Não, o queijo não é ruim",
  "O pão está fresco?",
  "Sim, o pão está fresco"
];
