export const phrases_ES = [
  "Necesito un médico",
  "¿Dónde está la guardia?",
  "Necesito que venga la enfermera",
  "Me duele el estómago",
  "Me siento enfermo",
  "¿Dónde está el hospital?",
  "Me duele la espalda",
  "Necesitaré una receta",
  "¿Tiene fiebre?",
  "No tengo fiebre",
  "Tengo dolor de cabeza",
  "Me duele la garganta",
  "Estoy tosiendo",
  "Tengo náuseas",
  "¿Dónde está la farmacia?",
  "Necesito medicinas",
  "¿Cuál es mi diagnóstico?",
  "¿Cuántas pastillas debo tomar?",
  "Tengo alergia",
  "Necesito una ambulancia",
  "Llama a emergencias",
  "¿Puede ayudarme?",
  "Me siento débil",
  "Tengo mucho cansancio",
  "¿Cuál es el precio?",
  "Necesito un análisis de sangre",
  "¿Tiene diabetes?",
  "No tengo diabetes",
  "¿Toma medicinas?",
  "Sí, tomo medicinas",
  "Me duele el pecho",
  "Tengo presión alta",
  "Tengo presión baja",
  "¿Puede examinarme?",
  "Abra la boca por favor",
  "Respire profundamente",
  "Levante el brazo",
  "¿Cuándo debo volver?",
  "Dentro de una semana",
  "Mañana vengo de nuevo",
  "¿Necesito reposo?",
  "Sí, necesita reposo absoluto",
  "Manténgase hidratado",
  "Evite alimentos pesados",
  "No beba alcohol",
  "Duerma bien",
  "Haga ejercicio moderado",
  "Tome vitaminas",
  "Coma frutas y verduras",
  "¿Tiene dolor crónico?",
  "El dolor empezó ayer",
  "El dolor empezó hace una semana",
  "¿Está embarazada?",
  "No estoy embarazada",
  "Necesito un ultrasonido",
  "¿Puede hacerme una radiografía?",
  "¿Cuáles son mis síntomas?",
  "Me falta aire",
  "No puedo dormir bien",
  "Tengo inflamación",
  "Tengo una herida abierta",
  "Necesito puntos de sutura",
  "¿Me va a doler?",
  "No le dolará mucho",
  "Esto es temporal",
  "Volverá a estar bien",
  "Descanse bastante",
  "¿Tiene seguimiento médico?",
  "Sí, tengo médico regular",
  "No, es mi primera vez aquí"
];

export const phrases_EN = [
  "I need a doctor",
  "Where is the medical clinic?",
  "I need a nurse",
  "I have a stomachache",
  "I feel sick",
  "Where is the hospital?",
  "My back hurts",
  "I will need a prescription",
  "Do you have a fever?",
  "I do not have a fever",
  "I have a headache",
  "My throat hurts",
  "I am coughing",
  "I feel nauseous",
  "Where is the pharmacy?",
  "I need medicines",
  "What is my diagnosis?",
  "How many pills should I take?",
  "I have allergies",
  "I need an ambulance",
  "Call emergency",
  "Can you help me?",
  "I feel weak",
  "I am very tired",
  "What is the price?",
  "I need a blood test",
  "Do you have diabetes?",
  "I do not have diabetes",
  "Do you take medicines?",
  "Yes, I take medicines",
  "I have chest pain",
  "I have high blood pressure",
  "I have low blood pressure",
  "Can you examine me?",
  "Open your mouth please",
  "Breathe deeply",
  "Raise your arm",
  "When should I return?",
  "In one week",
  "I will come again tomorrow",
  "Do I need rest?",
  "Yes, you need absolute rest",
  "Stay hydrated",
  "Avoid heavy foods",
  "Do not drink alcohol",
  "Sleep well",
  "Do moderate exercise",
  "Take vitamins",
  "Eat fruits and vegetables",
  "Do you have chronic pain?",
  "The pain started yesterday",
  "The pain started a week ago",
  "Are you pregnant?",
  "I am not pregnant",
  "I need an ultrasound",
  "Can you do an X-ray?",
  "What are my symptoms?",
  "I am short of breath",
  "I cannot sleep well",
  "I have inflammation",
  "I have an open wound",
  "I need stitches",
  "Will it hurt?",
  "It will not hurt much",
  "This is temporary",
  "You will be well again",
  "Rest plenty",
  "Do you have medical follow-up?",
  "Yes, I have a regular doctor",
  "No, it is my first time here"
];

export const phrases_DE = [
  "Ich brauche einen Arzt",
  "Wo ist die ärztliche Klinik?",
  "Ich brauche eine Krankenschwester",
  "Ich habe Bauchschmerzen",
  "Mir ist nicht gut",
  "Wo ist das Krankenhaus?",
  "Mein Rücken tut weh",
  "Ich brauche ein Rezept",
  "Haben Sie Fieber?",
  "Ich habe kein Fieber",
  "Ich habe Kopfschmerzen",
  "Mein Hals tut weh",
  "Ich huste",
  "Mir ist übel",
  "Wo ist die Apotheke?",
  "Ich brauche Medikamente",
  "Was ist meine Diagnose?",
  "Wie viele Pillen sollte ich nehmen?",
  "Ich habe Allergien",
  "Ich brauche einen Krankenwagen",
  "Rufen Sie den Notarzt",
  "Können Sie mir helfen?",
  "Ich fühle mich schwach",
  "Ich bin sehr müde",
  "Wie viel kostet das?",
  "Ich brauche einen Bluttest",
  "Haben Sie Diabetes?",
  "Ich habe kein Diabetes",
  "Nehmen Sie Medikamente?",
  "Ja, ich nehme Medikamente",
  "Ich habe Brustschmerzen",
  "Ich habe Bluthochdruck",
  "Ich habe niedrigen Blutdruck",
  "Können Sie mich untersuchen?",
  "Öffnen Sie bitte den Mund",
  "Atmen Sie tief ein",
  "Heben Sie Ihren Arm",
  "Wann sollte ich wiederkommen?",
  "In einer Woche",
  "Ich komme morgen wieder",
  "Brauche ich Ruhe?",
  "Ja, Sie brauchen absolute Ruhe",
  "Bleiben Sie hydratisiert",
  "Vermeiden Sie schwere Lebensmittel",
  "Trinken Sie keinen Alkohol",
  "Schlafen Sie gut",
  "Treiben Sie mäßig Sport",
  "Nehmen Sie Vitamine",
  "Essen Sie Obst und Gemüse",
  "Haben Sie chronische Schmerzen?",
  "Der Schmerz begann gestern",
  "Der Schmerz begann vor einer Woche",
  "Sind Sie schwanger?",
  "Ich bin nicht schwanger",
  "Ich brauche einen Ultraschall",
  "Können Sie ein Röntgenbild machen?",
  "Was sind meine Symptome?",
  "Mir fehlt die Luft",
  "Ich kann nicht gut schlafen",
  "Ich habe Schwellungen",
  "Ich habe eine offene Wunde",
  "Ich brauche Nähte",
  "Wird es weh tun?",
  "Es wird nicht viel weh tun",
  "Das ist vorübergehend",
  "Es wird dir bald besser gehen",
  "Ruhen Sie sich ausgiebig aus",
  "Haben Sie eine ärztliche Betreuung?",
  "Ja, ich habe einen regelmäßigen Arzt",
  "Nein, es ist mein erstes Mal hier"
];

export const phrases_IT = [
  "Ho bisogno di un medico",
  "Dov'è la clinica medica?",
  "Ho bisogno di un'infermiera",
  "Mi fa male lo stomaco",
  "Mi sento male",
  "Dov'è l'ospedale?",
  "Mi fa male la schiena",
  "Avrò bisogno di una ricetta",
  "Ha la febbre?",
  "Non ho la febbre",
  "Ho mal di testa",
  "Mi fa male la gola",
  "Sto tossendo",
  "Mi sento nauseato",
  "Dov'è la farmacia?",
  "Ho bisogno di medicinali",
  "Qual è la mia diagnosi?",
  "Quante pillole devo prendere?",
  "Ho allergie",
  "Ho bisogno di un'ambulanza",
  "Chiama i servizi di emergenza",
  "Puoi aiutarmi?",
  "Mi sento debole",
  "Sono molto stanco",
  "Qual è il prezzo?",
  "Ho bisogno di un esame del sangue",
  "Hai il diabete?",
  "Non ho il diabete",
  "Prendi medicinali?",
  "Sì, prendo medicinali",
  "Ho dolore al petto",
  "Ho la pressione alta",
  "Ho la pressione bassa",
  "Puoi visitarmi?",
  "Apri la bocca per favore",
  "Respira profondamente",
  "Alza il braccio",
  "Quando devo tornare?",
  "Tra una settimana",
  "Torno domani",
  "Ho bisogno di riposo?",
  "Sì, hai bisogno di riposo assoluto",
  "Rimani idratato",
  "Evita cibi pesanti",
  "Non bere alcol",
  "Dormi bene",
  "Fai esercizio moderato",
  "Prendi vitamine",
  "Mangia frutta e verdura",
  "Hai dolore cronico?",
  "Il dolore è iniziato ieri",
  "Il dolore è iniziato una settimana fa",
  "Sei incinta?",
  "Non sono incinta",
  "Ho bisogno di un'ecografia",
  "Puoi fare una radiografia?",
  "Quali sono i miei sintomi?",
  "Mi manca il respiro",
  "Non riesco a dormire bene",
  "Ho gonfiore",
  "Ho una ferita aperta",
  "Ho bisogno di punti di sutura",
  "Farà male?",
  "Non farà molto male",
  "Questo è temporaneo",
  "Starai di nuovo bene",
  "Riposati molto",
  "Hai un follow-up medico?",
  "Sì, ho un medico regolare",
  "No, è la mia prima volta qui"
];

export const phrases_PT = [
  "Preciso de um médico",
  "Onde fica a clínica médica?",
  "Preciso de uma enfermeira",
  "Meu estômago dói",
  "Estou me sentindo mal",
  "Onde fica o hospital?",
  "Minhas costas doem",
  "Vou precisar de uma receita",
  "Você tem febre?",
  "Não tenho febre",
  "Tenho dor de cabeça",
  "Minha garganta dói",
  "Estou tossindo",
  "Estou com náuseas",
  "Onde fica a farmácia?",
  "Preciso de medicamentos",
  "Qual é meu diagnóstico?",
  "Quantos comprimidos devo tomar?",
  "Tenho alergias",
  "Preciso de uma ambulância",
  "Chame emergência",
  "Você pode me ajudar?",
  "Estou me sentindo fraco",
  "Estou muito cansado",
  "Qual é o preço?",
  "Preciso de um exame de sangue",
  "Você tem diabetes?",
  "Não tenho diabetes",
  "Você toma medicamentos?",
  "Sim, tomo medicamentos",
  "Tenho dor no peito",
  "Tenho pressão alta",
  "Tenho pressão baixa",
  "Você pode me examinar?",
  "Abra a boca por favor",
  "Respire profundamente",
  "Levante o braço",
  "Quando devo voltar?",
  "Em uma semana",
  "Volto amanhã",
  "Preciso descansar?",
  "Sim, você precisa de repouso absoluto",
  "Mantenha-se hidratado",
  "Evite alimentos pesados",
  "Não beba álcool",
  "Durma bem",
  "Faça exercício moderado",
  "Tome vitaminas",
  "Coma frutas e vegetais",
  "Você tem dor crônica?",
  "A dor começou ontem",
  "A dor começou uma semana atrás",
  "Você está grávida?",
  "Não estou grávida",
  "Preciso de uma ultrassom",
  "Você pode fazer um raio-X?",
  "Quais são meus sintomas?",
  "Estou com falta de ar",
  "Não consigo dormir bem",
  "Tenho inchaço",
  "Tenho uma ferida aberta",
  "Preciso de pontos de sutura",
  "Vai doer?",
  "Não vai doer muito",
  "Isso é temporário",
  "Você ficará bem novamente",
  "Descanse bastante",
  "Você tem acompanhamento médico?",
  "Sim, tenho um médico regular",
  "Não, é minha primeira vez aqui"
];

export const phrases_FR = [
  "J'ai besoin d'un médecin",
  "Où est la clinique médicale?",
  "J'ai besoin d'une infirmière",
  "J'ai mal à l'estomac",
  "Je me sens mal",
  "Où est l'hôpital?",
  "J'ai mal au dos",
  "J'aurai besoin d'une ordonnance",
  "Avez-vous de la fièvre?",
  "Je n'ai pas de fièvre",
  "J'ai mal à la tête",
  "J'ai mal à la gorge",
  "Je tousse",
  "J'ai des nausées",
  "Où est la pharmacie?",
  "J'ai besoin de médicaments",
  "Quel est mon diagnostic?",
  "Combien de comprimés dois-je prendre?",
  "J'ai des allergies",
  "J'ai besoin d'une ambulance",
  "Appelez les urgences",
  "Pouvez-vous m'aider?",
  "Je me sens faible",
  "Je suis très fatigué",
  "Quel est le prix?",
  "J'ai besoin d'une prise de sang",
  "Avez-vous le diabète?",
  "Je n'ai pas le diabète",
  "Prenez-vous des médicaments?",
  "Oui, je prends des médicaments",
  "J'ai une douleur thoracique",
  "J'ai une tension artérielle élevée",
  "J'ai une tension artérielle basse",
  "Pouvez-vous m'examiner?",
  "Ouvrez la bouche s'il vous plaît",
  "Respirez profondément",
  "Levez votre bras",
  "Quand dois-je revenir?",
  "Dans une semaine",
  "Je reviens demain",
  "Ai-je besoin de repos?",
  "Oui, vous avez besoin de repos absolu",
  "Restez hydraté",
  "Évitez les aliments lourds",
  "Ne buvez pas d'alcool",
  "Dormez bien",
  "Faites de l'exercice modéré",
  "Prenez des vitamines",
  "Mangez des fruits et des légumes",
  "Avez-vous une douleur chronique?",
  "La douleur a commencé hier",
  "La douleur a commencé il y a une semaine",
  "Êtes-vous enceinte?",
  "Je ne suis pas enceinte",
  "J'ai besoin d'une échographie",
  "Pouvez-vous faire une radiographie?",
  "Quels sont mes symptômes?",
  "Je manque de souffle",
  "Je ne peux pas bien dormir",
  "J'ai une inflammation",
  "J'ai une plaie ouverte",
  "J'ai besoin de points de suture",
  "Est-ce que ça va faire mal?",
  "Ce ne sera pas très douloureux",
  "C'est temporaire",
  "Vous allez bien bientôt",
  "Reposez-vous beaucoup",
  "Avez-vous un suivi médical?",
  "Oui, j'ai un médecin régulier",
  "Non, c'est la première fois ici"
];
