export const phrases_ES = [
  "Quiero manzanas",
  "Necesito pan",
  "Busco leche",
  "¿Dónde encuentro las bananas?",
  "¿Cuánto cuesta el queso?",
  "Quiero pagar ahora",
  "¿Dónde pago?",
  "¿Puede darme una bolsa?",
  "¿Tiene ofertas hoy?",
  "Quiero arroz",
  "Necesito agua",
  "Busco tomates",
  "¿Dónde está la carne?",
  "¿Cuánto cuesta el pollo?",
  "Quiero café",
  "Necesito azúcar",
  "Busco sal",
  "¿Dónde encuentro las naranjas?",
  "¿Cuánto cuesta la manteca?",
  "Quiero huevos",
  "Necesito harina",
  "Busco aceite",
  "¿Dónde está el pescado?",
  "¿Cuánto cuesta la cerveza?",
  "Quiero jugo",
  "Necesito yogur",
  "Busco galletas",
  "¿Dónde encuentro las papas?",
  "¿Cuánto cuesta el chocolate?",
  "Quiero té",
  "Necesito miel",
  "Busco cebollas",
  "¿Dónde está el arroz?",
  "¿Cuánto cuesta la leche?",
  "Quiero zanahorias",
  "Necesito jabón",
  "Busco papel higiénico",
  "¿Dónde encuentro el vino?",
  "¿Cuánto cuesta el agua?",
  "Quiero mantequilla",
  "Necesito queso",
  "Busco frutas",
  "¿Dónde está el pan?",
  "¿Cuánto cuesta la carne?",
  "Quiero verduras",
  "Necesito pollo",
  "Busco pescado",
  "¿Dónde encuentro las uvas?",
  "¿Cuánto cuesta el café?",
  "Quiero azúcar",
  "Necesito sal",
  "Busco harina",
  "¿Dónde está el aceite?",
  "¿Cuánto cuesta el jugo?",
  "Quiero yogur",
  "Necesito galletas",
  "Busco chocolate",
  "¿Dónde encuentro las zanahorias?",
  "¿Cuánto cuesta el té?",
  "Quiero miel",
  "Necesito cebollas",
  "Busco papas",
  "¿Dónde está el jabón?",
  "¿Cuánto cuesta el vino?",
  "Quiero agua",
  "Necesito frutas",
  "Busco verduras",
  "¿Dónde encuentro el pollo?",
  "¿Cuánto cuesta el pescado?",
  "Quiero pan",
  "Necesito leche"
];

export const phrases_EN = [
  "I want apples",
  "I need bread",
  "I am looking for milk",
  "Where do I find bananas?",
  "How much is the cheese?",
  "I want to pay now",
  "Where do I pay?",
  "Can you give me a bag?",
  "Do you have offers today?",
  "I want rice",
  "I need water",
  "I am looking for tomatoes",
  "Where is the meat?",
  "How much is the chicken?",
  "I want coffee",
  "I need sugar",
  "I am looking for salt",
  "Where do I find oranges?",
  "How much is the butter?",
  "I want eggs",
  "I need flour",
  "I am looking for oil",
  "Where is the fish?",
  "How much is the beer?",
  "I want juice",
  "I need yogurt",
  "I am looking for cookies",
  "Where do I find potatoes?",
  "How much is the chocolate?",
  "I want tea",
  "I need honey",
  "I am looking for onions",
  "Where is the rice?",
  "How much is the milk?",
  "I want carrots",
  "I need soap",
  "I am looking for toilet paper",
  "Where do I find wine?",
  "How much is the water?",
  "I want butter",
  "I need cheese",
  "I am looking for fruits",
  "Where is the bread?",
  "How much is the meat?",
  "I want vegetables",
  "I need chicken",
  "I am looking for fish",
  "Where do I find grapes?",
  "How much is the coffee?",
  "I want sugar",
  "I need salt",
  "I am looking for flour",
  "Where is the oil?",
  "How much is the juice?",
  "I want yogurt",
  "I need cookies",
  "I am looking for chocolate",
  "Where do I find carrots?",
  "How much is the tea?",
  "I want honey",
  "I need onions",
  "I am looking for potatoes",
  "Where is the soap?",
  "How much is the wine?",
  "I want water",
  "I need fruits",
  "I am looking for vegetables",
  "Where do I find chicken?",
  "How much is the fish?",
  "I want bread",
  "I need milk"
];

export const phrases_DE = [
  "Ich möchte Äpfel",
  "Ich brauche Brot",
  "Ich suche Milch",
  "Wo finde ich Bananen?",
  "Wie viel kostet der Käse?",
  "Ich möchte jetzt bezahlen",
  "Wo bezahle ich?",
  "Können Sie mir eine Tüte geben?",
  "Haben Sie heute Angebote?",
  "Ich möchte Reis",
  "Ich brauche Wasser",
  "Ich suche Tomaten",
  "Wo ist das Fleisch?",
  "Wie viel kostet das Huhn?",
  "Ich möchte Kaffee",
  "Ich brauche Zucker",
  "Ich suche Salz",
  "Wo finde ich Orangen?",
  "Wie viel kostet die Butter?",
  "Ich möchte Eier",
  "Ich brauche Mehl",
  "Ich suche Öl",
  "Wo ist der Fisch?",
  "Wie viel kostet das Bier?",
  "Ich möchte Saft",
  "Ich brauche Joghurt",
  "Ich suche Kekse",
  "Wo finde ich Kartoffeln?",
  "Wie viel kostet die Schokolade?",
  "Ich möchte Tee",
  "Ich brauche Honig",
  "Ich suche Zwiebeln",
  "Wo ist der Reis?",
  "Wie viel kostet die Milch?",
  "Ich möchte Karotten",
  "Ich brauche Seife",
  "Ich suche Toilettenpapier",
  "Wo finde ich Wein?",
  "Wie viel kostet das Wasser?",
  "Ich möchte Butter",
  "Ich brauche Käse",
  "Ich suche Obst",
  "Wo ist das Brot?",
  "Wie viel kostet das Fleisch?",
  "Ich möchte Gemüse",
  "Ich brauche Huhn",
  "Ich suche Fisch",
  "Wo finde ich Trauben?",
  "Wie viel kostet der Kaffee?",
  "Ich möchte Zucker",
  "Ich brauche Salz",
  "Ich suche Mehl",
  "Wo ist das Öl?",
  "Wie viel kostet der Saft?",
  "Ich möchte Joghurt",
  "Ich brauche Kekse",
  "Ich suche Schokolade",
  "Wo finde ich Karotten?",
  "Wie viel kostet der Tee?",
  "Ich möchte Honig",
  "Ich brauche Zwiebeln",
  "Ich suche Kartoffeln",
  "Wo ist die Seife?",
  "Wie viel kostet der Wein?",
  "Ich möchte Wasser",
  "Ich brauche Obst",
  "Ich suche Gemüse",
  "Wo finde ich Huhn?",
  "Wie viel kostet der Fisch?",
  "Ich möchte Brot",
  "Ich brauche Milch"
];

export const phrases_IT = [
  "Voglio mele",
  "Ho bisogno di pane",
  "Cerco latte",
  "Dove trovo le banane?",
  "Quanto costa il formaggio?",
  "Voglio pagare adesso",
  "Dove pago?",
  "Può darmi una borsa?",
  "Ha offerte oggi?",
  "Voglio riso",
  "Ho bisogno di acqua",
  "Cerco pomodori",
  "Dov'è la carne?",
  "Quanto costa il pollo?",
  "Voglio caffè",
  "Ho bisogno di zucchero",
  "Cerco sale",
  "Dove trovo le arance?",
  "Quanto costa il burro?",
  "Voglio uova",
  "Ho bisogno di farina",
  "Cerco olio",
  "Dov'è il pesce?",
  "Quanto costa la birra?",
  "Voglio succo",
  "Ho bisogno di yogurt",
  "Cerco biscotti",
  "Dove trovo le patate?",
  "Quanto costa il cioccolato?",
  "Voglio tè",
  "Ho bisogno di miele",
  "Cerco cipolle",
  "Dov'è il riso?",
  "Quanto costa il latte?",
  "Voglio carote",
  "Ho bisogno di sapone",
  "Cerco carta igienica",
  "Dove trovo il vino?",
  "Quanto costa l'acqua?",
  "Voglio burro",
  "Ho bisogno di formaggio",
  "Cerco frutta",
  "Dov'è il pane?",
  "Quanto costa la carne?",
  "Voglio verdure",
  "Ho bisogno di pollo",
  "Cerco pesce",
  "Dove trovo l'uva?",
  "Quanto costa il caffè?",
  "Voglio zucchero",
  "Ho bisogno di sale",
  "Cerco farina",
  "Dov'è l'olio?",
  "Quanto costa il succo?",
  "Voglio yogurt",
  "Ho bisogno di biscotti",
  "Cerco cioccolato",
  "Dove trovo le carote?",
  "Quanto costa il tè?",
  "Voglio miele",
  "Ho bisogno di cipolle",
  "Cerco patate",
  "Dov'è il sapone?",
  "Quanto costa il vino?",
  "Voglio acqua",
  "Ho bisogno di frutta",
  "Cerco verdure",
  "Dove trovo il pollo?",
  "Quanto costa il pesce?",
  "Voglio pane",
  "Ho bisogno di latte"
];
