export const phrases_ES = [
  "Quiero el menú",
  "Tengo hambre",
  "La sopa está caliente",
  "El café es bueno",
  "La mesa está limpia",
  "El camarero es amable",
  "La comida está lista",
  "El pan es fresco",
  "El vino es rojo",
  "La cuenta está aquí",
  "No quiero carne",
  "No tengo dinero",
  "No hay agua",
  "No me gusta la sopa",
  "No quiero postre",
  "No hay pan",
  "No está abierto",
  "No quiero vino",
  "No tengo reserva",
  "No hay mesa libre",
  "¿Dónde está el baño?",
  "¿Cuánto cuesta?",
  "¿Tienen pescado?",
  "¿Está abierto?",
  "¿Puedo pagar con tarjeta?",
  "¿Hay mesa para dos?",
  "¿Qué recomienda?",
  "¿Dónde está la cocina?",
  "¿Tienen cerveza?",
  "¿Está frío el café?",
  "Quiero agua con limón",
  "Quiero pan y manteca",
  "Quiero arroz con pollo",
  "Quiero pizza sin queso",
  "Quiero carne o pescado",
  "Quiero café y té",
  "Quiero sopa con pan",
  "Quiero vino sin alcohol",
  "Quiero ensalada con tomate",
  "Quiero postre y café",
  "No quiero agua con gas",
  "No quiero pan duro",
  "No quiero arroz frío",
  "No quiero pizza grande",
  "No quiero carne cruda",
  "¿Dónde está el camarero?",
  "¿Cuánto cuesta la pizza?",
  "¿Tienen menú del día?",
  "¿Está lista la comida?",
  "¿Puedo pedir ahora?",
  "Quiero reservar una mesa",
  "Quiero una mesa afuera",
  "Quiero una mesa adentro",
  "Quiero una mesa cerca de la ventana",
  "Quiero una mesa tranquila",
  "Quiero un vaso de agua",
  "Quiero un jugo de naranja",
  "Quiero una cerveza fría",
  "Quiero una copa de vino",
  "Quiero un café con leche",
  "¿Tienen jugo de manzana?",
  "¿Tienen vino blanco?",
  "¿Tienen café descafeinado?",
  "¿Tienen té negro?",
  "¿Tienen agua mineral?",
  "¿Está abierto en la noche?",
  "¿Está abierto el domingo?",
  "¿Puedo reservar por teléfono?",
  "¿Puedo pagar en efectivo?",
  "¿Qué postre recomienda?",
  "¿Qué bebida recomienda?",
  "¿Qué plato recomienda?",
  "¿Qué vino recomienda?"
];

export const phrases_EN = [
  "I want the menu",
  "I am hungry",
  "The soup is hot",
  "The coffee is good",
  "The table is clean",
  "The waiter is kind",
  "The food is ready",
  "The bread is fresh",
  "The wine is red",
  "The bill is here",
  "I don't want meat",
  "I don't have money",
  "There is no water",
  "I don't like the soup",
  "I don't want dessert",
  "There is no bread",
  "It is not open",
  "I don't want wine",
  "I don't have a reservation",
  "There is no free table",
  "Where is the bathroom?",
  "How much does it cost?",
  "Do you have fish?",
  "Is it open?",
  "Can I pay with card?",
  "Is there a table for two?",
  "What do you recommend?",
  "Where is the kitchen?",
  "Do you have beer?",
  "Is the coffee cold?",
  "I want water with lemon",
  "I want bread and butter",
  "I want rice with chicken",
  "I want pizza without cheese",
  "I want meat or fish",
  "I want coffee and tea",
  "I want soup with bread",
  "I want wine without alcohol",
  "I want salad with tomato",
  "I want dessert and coffee",
  "I don't want sparkling water",
  "I don't want hard bread",
  "I don't want cold rice",
  "I don't want a big pizza",
  "I don't want raw meat",
  "Where is the waiter?",
  "How much is the pizza?",
  "Do you have today's menu?",
  "Is the food ready?",
  "Can I order now?",
  "I want to reserve a table",
  "I want a table outside",
  "I want a table inside",
  "I want a table near the window",
  "I want a quiet table",
  "I want a glass of water",
  "I want orange juice",
  "I want a cold beer",
  "I want a glass of wine",
  "I want coffee with milk",
  "Do you have apple juice?",
  "Do you have white wine?",
  "Do you have decaf coffee?",
  "Do you have black tea?",
  "Do you have mineral water?",
  "Is it open at night?",
  "Is it open on Sunday?",
  "Can I reserve by phone?",
  "Can I pay in cash?",
  "What dessert do you recommend?",
  "What drink do you recommend?",
  "What dish do you recommend?",
  "What wine do you recommend?"
];

export const phrases_DE = [
  "Ich möchte die Speisekarte",
  "Ich habe Hunger",
  "Die Suppe ist heiß",
  "Der Kaffee ist gut",
  "Der Tisch ist sauber",
  "Der Kellner ist freundlich",
  "Das Essen ist fertig",
  "Das Brot ist frisch",
  "Der Wein ist rot",
  "Die Rechnung ist hier",
  "Ich will kein Fleisch",
  "Ich habe kein Geld",
  "Es gibt kein Wasser",
  "Ich mag die Suppe nicht",
  "Ich will keinen Nachtisch",
  "Es gibt kein Brot",
  "Es ist nicht geöffnet",
  "Ich will keinen Wein",
  "Ich habe keine Reservierung",
  "Es gibt keinen freien Tisch",
  "Wo ist die Toilette?",
  "Wie viel kostet es?",
  "Haben Sie Fisch?",
  "Ist es geöffnet?",
  "Kann ich mit Karte zahlen?",
  "Gibt es einen Tisch für zwei?",
  "Was empfehlen Sie?",
  "Wo ist die Küche?",
  "Haben Sie Bier?",
  "Ist der Kaffee kalt?",
  "Ich möchte Wasser mit Zitrone",
  "Ich möchte Brot und Butter",
  "Ich möchte Reis mit Huhn",
  "Ich möchte Pizza ohne Käse",
  "Ich möchte Fleisch oder Fisch",
  "Ich möchte Kaffee und Tee",
  "Ich möchte Suppe mit Brot",
  "Ich möchte Wein ohne Alkohol",
  "Ich möchte Salat mit Tomate",
  "Ich möchte Nachtisch und Kaffee",
  "Ich will kein Sprudelwasser",
  "Ich will kein hartes Brot",
  "Ich will keinen kalten Reis",
  "Ich will keine große Pizza",
  "Ich will kein rohes Fleisch",
  "Wo ist der Kellner?",
  "Wie viel kostet die Pizza?",
  "Haben Sie das Tagesmenü?",
  "Ist das Essen fertig?",
  "Kann ich jetzt bestellen?",
  "Ich möchte einen Tisch reservieren",
  "Ich möchte einen Tisch draußen",
  "Ich möchte einen Tisch drinnen",
  "Ich möchte einen Tisch am Fenster",
  "Ich möchte einen ruhigen Tisch",
  "Ich möchte ein Glas Wasser",
  "Ich möchte Orangensaft",
  "Ich möchte ein kaltes Bier",
  "Ich möchte ein Glas Wein",
  "Ich möchte Kaffee mit Milch",
  "Haben Sie Apfelsaft?",
  "Haben Sie Weißwein?",
  "Haben Sie entkoffeinierten Kaffee?",
  "Haben Sie schwarzen Tee?",
  "Haben Sie Mineralwasser?",
  "Ist es abends geöffnet?",
  "Ist es am Sonntag geöffnet?",
  "Kann ich telefonisch reservieren?",
  "Kann ich bar bezahlen?",
  "Welchen Nachtisch empfehlen Sie?",
  "Welches Getränk empfehlen Sie?",
  "Welches Gericht empfehlen Sie?",
  "Welchen Wein empfehlen Sie?"
];

export const phrases_IT = [
  "Voglio il menù",
  "Ho fame",
  "La zuppa è calda",
  "Il caffè è buono",
  "Il tavolo è pulito",
  "Il cameriere è gentile",
  "Il cibo è pronto",
  "Il pane è fresco",
  "Il vino è rosso",
  "Il conto è qui",
  "Non voglio carne",
  "Non ho soldi",
  "Non c'è acqua",
  "Non mi piace la zuppa",
  "Non voglio dolce",
  "Non c'è pane",
  "Non è aperto",
  "Non voglio vino",
  "Non ho prenotazione",
  "Non c'è tavolo libero",
  "Dove si trova il bagno?",
  "Quanto costa?",
  "Avete pesce?",
  "È aperto?",
  "Posso pagare con carta?",
  "C'è un tavolo per due?",
  "Cosa consiglia?",
  "Dove si trova la cucina?",
  "Avete birra?",
  "Il caffè è freddo?",
  "Voglio acqua con limone",
  "Voglio pane e burro",
  "Voglio riso con pollo",
  "Voglio pizza senza formaggio",
  "Voglio carne o pesce",
  "Voglio caffè e tè",
  "Voglio zuppa con pane",
  "Voglio vino senza alcol",
  "Voglio insalata con pomodoro",
  "Voglio dolce e caffè",
  "Non voglio acqua frizzante",
  "Non voglio pane duro",
  "Non voglio riso freddo",
  "Non voglio pizza grande",
  "Non voglio carne cruda",
  "Dove si trova il cameriere?",
  "Quanto costa la pizza?",
  "Avete menù del giorno?",
  "Il cibo è pronto?",
  "Posso ordinare adesso?",
  "Voglio prenotare un tavolo",
  "Voglio un tavolo fuori",
  "Voglio un tavolo dentro",
  "Voglio un tavolo vicino alla finestra",
  "Voglio un tavolo tranquillo",
  "Voglio un bicchiere d'acqua",
  "Voglio un succo d'arancia",
  "Voglio una birra fredda",
  "Voglio un bicchiere di vino",
  "Voglio un caffè con latte",
  "Avete succo di mela?",
  "Avete vino bianco?",
  "Avete caffè decaffeinato?",
  "Avete tè nero?",
  "Avete acqua minerale?",
  "È aperto di notte?",
  "È aperto la domenica?",
  "Posso prenotare per telefono?",
  "Posso pagare in contanti?",
  "Quale dolce consiglia?",
  "Quale bevanda consiglia?",
  "Quale piatto consiglia?",
  "Quale vino consiglia?"
];

export const phrases_PT = [
  "Eu quero o cardápio",
  "Estou com fome",
  "A sopa está quente",
  "O café é bom",
  "A mesa está limpa",
  "O garçom é amável",
  "A comida está pronta",
  "O pão é fresco",
  "O vinho é tinto",
  "A conta está aqui",
  "Não quero carne",
  "Não tenho dinheiro",
  "Não há água",
  "Não gosto da sopa",
  "Não quero sobremesa",
  "Não há pão",
  "Não está aberto",
  "Não quero vinho",
  "Não tenho reserva",
  "Não há mesa disponível",
  "Onde fica o banheiro?",
  "Quanto custa?",
  "Vocês têm peixe?",
  "Está aberto?",
  "Posso pagar com cartão?",
  "Há mesa para dois?",
  "O que você recomenda?",
  "Onde fica a cozinha?",
  "Vocês têm cerveja?",
  "O café está frio?",
  "Quero água com limão",
  "Quero pão e manteiga",
  "Quero arroz com frango",
  "Quero pizza sem queijo",
  "Quero carne ou peixe",
  "Quero café e chá",
  "Quero sopa com pão",
  "Quero vinho sem álcool",
  "Quero salada com tomate",
  "Quero sobremesa e café",
  "Não quero água com gás",
  "Não quero pão duro",
  "Não quero arroz frio",
  "Não quero pizza grande",
  "Não quero carne crua",
  "Onde está o garçom?",
  "Quanto custa a pizza?",
  "Vocês têm prato do dia?",
  "A comida está pronta?",
  "Posso pedir agora?",
  "Quero reservar uma mesa",
  "Quero uma mesa lá fora",
  "Quero uma mesa dentro",
  "Quero uma mesa perto da janela",
  "Quero uma mesa tranquila",
  "Quero um copo de água",
  "Quero um suco de laranja",
  "Quero uma cerveja fria",
  "Quero uma taça de vinho",
  "Quero um café com leite",
  "Vocês têm suco de maçã?",
  "Vocês têm vinho branco?",
  "Vocês têm café descafeinado?",
  "Vocês têm chá preto?",
  "Vocês têm água mineral?",
  "Está aberto à noite?",
  "Está aberto no domingo?",
  "Posso reservar por telefone?",
  "Posso pagar em dinheiro?",
  "Qual sobremesa você recomenda?",
  "Qual bebida você recomenda?",
  "Qual prato você recomenda?",
  "Qual vinho você recomenda?"
];
